const $=id=>document.getElementById(id),g=9.81; let t=0,running=false,last=0;
function arrow(ctx,x1,y1,x2,y2,label){ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();let a=Math.atan2(y2-y1,x2-x1),s=9;ctx.beginPath();ctx.moveTo(x2,y2);ctx.lineTo(x2-s*Math.cos(a-.5),y2-s*Math.sin(a-.5));ctx.lineTo(x2-s*Math.cos(a+.5),y2-s*Math.sin(a+.5));ctx.closePath();ctx.fill();ctx.fillText(label,x2+7,y2-5)}
function newton(){let m=+$('mass').value||1,F=+$('force').value||0,mu=+$('mu').value||0,fr=$('friction').checked?mu*m*g:0,net=F===0?0:F-Math.sign(F)*fr;if(F&&Math.sign(F)!==Math.sign(net))net=0;let a=net/m,v=a*t,x=.5*a*t*t;$('netF').textContent=net.toFixed(1)+' N';$('accel').textContent=a.toFixed(2)+' m/s²';$('vel').textContent=v.toFixed(2)+' m/s';$('pos').textContent=x.toFixed(2)+' m';$('newtonFormula').innerHTML=`F<sub>roce</sub> = ${fr.toFixed(1)} N<br>ΣF = ${net.toFixed(1)} N<br><b>a = ${a.toFixed(2)} m/s²</b>`;let c=$('newtonCanvas'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);q.strokeStyle='#777';q.fillStyle='#333';q.lineWidth=3;q.beginPath();q.moveTo(30,270);q.lineTo(770,270);q.stroke();let px=Math.max(90,Math.min(690,160+x*4));q.fillStyle='#8d3aa1';q.fillRect(px,210,100,60);q.fillStyle='#333';q.strokeStyle='#333';arrow(q,px+50,210,px+50,130,'N');arrow(q,px+50,240,px+50,330,'mg');if(F)arrow(q,px+100,240,px+100+Math.sign(F)*Math.min(130,Math.abs(F)*4),240,'F');if(fr)arrow(q,px,255,px-Math.sign(F)*Math.min(110,fr*4),255,'fₖ')}
function loop(ts){if(running){if(last)t+=(ts-last)/1000;last=ts;newton()}requestAnimationFrame(loop)}requestAnimationFrame(loop);$('play').onclick=()=>{running=true;last=0};$('pause').onclick=()=>running=false;$('reset').onclick=()=>{running=false;t=0;newton()};['mass','force','mu','friction'].forEach(x=>$(x).oninput=newton);
function dcl(){
 let mode=$('dclMode').value,th=mode==='incline'?(+$('angle').value||0)*Math.PI/180:0,on=n=>document.querySelector(`[data-v=${n}]`).checked;
 function axes(q,cx,cy){q.strokeStyle='#777';q.fillStyle='#555';q.lineWidth=2;arrow(q,cx,cy,cx+105*Math.cos(th),cy-105*Math.sin(th),'x');arrow(q,cx,cy,cx-85*Math.sin(th),cy-85*Math.cos(th),'y')}
 let c=$('dclSceneCanvas'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);q.save();q.translate(300,235);q.rotate(-th);q.strokeStyle='#777';q.lineWidth=4;q.beginPath();q.moveTo(-240,45);q.lineTo(240,45);q.stroke();q.fillStyle='#8d3aa1';q.fillRect(-45,-15,90,60);q.restore();q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;let cx=300,cy=220;if(on('weight'))arrow(q,cx,cy,cx,cy+105,'mg');if(on('normal'))arrow(q,cx,cy-5,cx-85*Math.sin(th),cy-5-85*Math.cos(th),'N');if(on('applied'))arrow(q,cx+45*Math.cos(th),cy-45*Math.sin(th),cx+145*Math.cos(th),cy-145*Math.sin(th),'F');if(on('fric'))arrow(q,cx-35*Math.cos(th),cy+35*Math.sin(th),cx-125*Math.cos(th),cy+125*Math.sin(th),'f');
 c=$('dclCanvas');q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);cx=300;cy=185;axes(q,cx,cy);q.fillStyle='#211b25';q.beginPath();q.arc(cx,cy,7,0,2*Math.PI);q.fill();q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;if(on('weight'))arrow(q,cx,cy,cx,cy+120,'mg');if(on('normal'))arrow(q,cx,cy,cx-100*Math.sin(th),cy-100*Math.cos(th),'N');if(on('applied'))arrow(q,cx,cy,cx+120*Math.cos(th),cy-120*Math.sin(th),'F');if(on('fric'))arrow(q,cx,cy,cx-95*Math.cos(th),cy+95*Math.sin(th),'f');
 $('dclEquations').innerHTML=mode==='incline'?`Ejes: x paralelo al plano; y perpendicular.<br>ΣF<sub>x</sub> = F − f − mg sinθ = ma<sub>x</sub><br>ΣF<sub>y</sub> = N − mg cosθ = 0`:`Ejes: x horizontal; y vertical.<br>ΣF<sub>x</sub> = F − f = ma<sub>x</sub><br>ΣF<sub>y</sub> = N − mg = 0`;$('angleLabel').style.display=mode==='incline'?'flex':'none'
}
$('dclMode').onchange=dcl;$('angle').oninput=dcl;document.querySelectorAll('.vec').forEach(x=>x.onchange=dcl);
function constant(){let m=+$('cm').value||1,th=(+$('ctheta').value||0)*Math.PI/180,mu=+$('cmu').value||0,N=m*g*Math.cos(th),fp=m*g*Math.sin(th),fr=mu*N,a=(fp-fr)/m;
 let c=$('constantScene'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);q.save();q.translate(300,245);q.rotate(-th);q.strokeStyle='#777';q.lineWidth=5;q.beginPath();q.moveTo(-245,40);q.lineTo(245,40);q.stroke();q.fillStyle='#8d3aa1';q.fillRect(-45,-20,90,60);q.restore();q.fillStyle='#333';q.strokeStyle='#333';q.lineWidth=3;arrow(q,300,225,300,330,'mg');arrow(q,300,225,300-95*Math.sin(th),225-95*Math.cos(th),'N');arrow(q,300,225,300-90*Math.cos(th),225+90*Math.sin(th),'fₖ');
 c=$('constantDCL');q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);let cx=300,cy=180;q.fillStyle='#222';q.beginPath();q.arc(cx,cy,7,0,7);q.fill();q.strokeStyle='#777';q.fillStyle='#555';q.lineWidth=2;arrow(q,cx,cy,cx+105*Math.cos(th),cy-105*Math.sin(th),'x');arrow(q,cx,cy,cx-85*Math.sin(th),cy-85*Math.cos(th),'y');q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;arrow(q,cx,cy,cx,cy+115,'mg');arrow(q,cx,cy,cx-100*Math.sin(th),cy-100*Math.cos(th),'N');arrow(q,cx,cy,cx-95*Math.cos(th),cy+95*Math.sin(th),'fₖ');
 $('constantResult').innerHTML=`mg sinθ = <b>${fp.toFixed(2)} N</b> · N = <b>${N.toFixed(2)} N</b> · fₖ = <b>${fr.toFixed(2)} N</b> · a = <b>${a.toFixed(2)} m/s²</b>`;$('constantEq').innerHTML=`Eje x: mg sinθ − fₖ = ma<br>Eje y: N − mg cosθ = 0<br>fₖ = μₖN`}
['cm','ctheta','cmu'].forEach(x=>$(x).oninput=constant);
let springRunning=false,springT=0,springLast=0;
function springState(){let k=+$('k').value||1,m=+$('springM').value||1,A=+$('springX').value||0,omega=Math.sqrt(k/m),x=springRunning?A*Math.cos(omega*springT):A,F=-k*x,a=F/m;return{k,m,A,omega,x,F,a}}
function spring(){let z=springState(),{k,m,A,x,F,a}=z;$('springFormula').innerHTML=`x = <b>${x.toFixed(3)} m</b><br>F = −kx = <b>${F.toFixed(2)} N</b><br>a = F/m = <b>${a.toFixed(2)} m/s²</b>`;
 let c=$('springCanvas'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);let eq=310,end=eq+x*420;q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;q.fillRect(35,75,14,210);q.setLineDash([5,5]);q.strokeStyle='#aaa';q.beginPath();q.moveTo(eq,75);q.lineTo(eq,285);q.stroke();q.setLineDash([]);q.fillStyle='#777';q.fillText('x = 0',eq-15,305);q.strokeStyle='#333';q.beginPath();q.moveTo(49,180);for(let i=1;i<=12;i++){let xx=49+(end-49)*i/12,yy=180+(i%2?22:-22);q.lineTo(xx,yy)}q.lineTo(end,180);q.stroke();q.fillStyle='#8d3aa1';q.fillRect(end,145,80,70);q.strokeStyle='#c52884';q.fillStyle='#c52884';if(Math.abs(F)>.01)arrow(q,end+40,130,end+40+Math.sign(F)*Math.min(130,Math.abs(F)*12),130,'Fₑ');
 c=$('springDCL');q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);let cx=300,cy=175;q.fillStyle='#222';q.beginPath();q.arc(cx,cy,7,0,7);q.fill();q.strokeStyle='#777';q.fillStyle='#555';q.lineWidth=2;arrow(q,cx,cy,cx+100,cy,'x');arrow(q,cx,cy,cx,cy-90,'y');q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;arrow(q,cx,cy,cx,cy+95,'mg');arrow(q,cx,cy,cx,cy-95,'N');q.strokeStyle='#c52884';q.fillStyle='#c52884';if(Math.abs(F)>.01)arrow(q,cx,cy,cx+Math.sign(F)*Math.min(130,Math.abs(F)*12),cy,'Fₑ');
 c=$('springGraph');q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);let ox=c.width/2,oy=c.height/2,scaleX=600,scaleF=8;q.strokeStyle='#aaa';q.lineWidth=2;q.beginPath();q.moveTo(30,oy);q.lineTo(c.width-30,oy);q.moveTo(ox,20);q.lineTo(ox,c.height-20);q.stroke();q.fillStyle='#555';q.fillText('x',c.width-35,oy-8);q.fillText('F',ox+8,25);q.strokeStyle='#792c8c';q.lineWidth=3;q.beginPath();for(let px=30;px<c.width-30;px++){let xx=(px-ox)/scaleX,fy=-k*xx,py=oy-fy*scaleF;if(px===30)q.moveTo(px,py);else q.lineTo(px,py)}q.stroke();q.fillStyle='#c52884';q.beginPath();q.arc(ox+x*scaleX,oy-F*scaleF,7,0,7);q.fill();q.fillText('F(x)',45,35)}
function springLoop(ts){if(springRunning){if(springLast)springT+=(ts-springLast)/1000;springLast=ts;spring()}requestAnimationFrame(springLoop)}requestAnimationFrame(springLoop);$('springPlay').onclick=()=>{springRunning=true;springT=0;springLast=0};$('springPause').onclick=()=>springRunning=false;$('springReset').onclick=()=>{springRunning=false;springT=0;springLast=0;spring()};['k','springX','springM'].forEach(x=>$(x).oninput=()=>{springRunning=false;springT=0;spring()});
function circular(){let m=+$('circM').value||1,r=+$('radius').value||1,v=+$('speed').value||0,ac=v*v/r,Fr=m*ac;$('circFormula').innerHTML=`a<sub>c</sub> = v²/r = <b>${ac.toFixed(2)} m/s²</b><br>ΣF<sub>r</sub> = ma<sub>c</sub> = <b>${Fr.toFixed(2)} N</b>`;let c=$('circCanvas'),q=c.getContext('2d');q.clearRect(0,0,c.width,c.height);let cx=400,cy=215,R=Math.min(150,r*55);q.strokeStyle='#aaa';q.lineWidth=2;q.beginPath();q.arc(cx,cy,R,0,Math.PI*2);q.stroke();let x=cx+R,y=cy;q.fillStyle='#8d3aa1';q.beginPath();q.arc(x,y,15,0,Math.PI*2);q.fill();q.strokeStyle='#333';q.fillStyle='#333';q.lineWidth=3;if($('showV').checked)arrow(q,x,y,x,y-120,'v');if($('showAc').checked)arrow(q,x,y,x-120,y,'aᶜ');if($('showFr').checked){q.strokeStyle='#c52884';q.fillStyle='#c52884';arrow(q,x,y+25,x-120,y+25,'ΣFᵣ')}}['circM','radius','speed','showV','showAc','showFr'].forEach(x=>$(x).oninput=circular);
const qs=[{q:'Un bloque de 4 kg recibe una fuerza neta horizontal de 12 N. ¿Cuál es su aceleración en m/s²?',a:3,h:'Usa ΣF = ma.'},{q:'Un automóvil de 1000 kg se mueve a 10 m/s en una curva de radio 50 m. ¿Cuál es la fuerza radial neta en N?',a:2000,h:'Usa ΣFᵣ = mv²/r.'},{q:'Un resorte de k = 40 N/m se estira 0,20 m. ¿Cuál es la magnitud de la fuerza elástica en N?',a:8,h:'Usa |F| = k|x|.'},{q:'Un bloque de 2 kg está en reposo sobre una mesa horizontal. ¿Cuál es la normal en N? Usa g = 9,81 m/s².',a:19.62,h:'En vertical, ΣFᵧ = 0.'}];let qi=0;function question(){$('question').innerHTML=`<h3>Ejercicio ${qi+1}</h3><p>${qs[qi].q}</p>`;$('answer').value='';$('feedback').textContent=''}$('check').onclick=()=>{let z=+$('answer').value,ok=Math.abs(z-qs[qi].a)<Math.max(.02,Math.abs(qs[qi].a)*.01);$('feedback').textContent=ok?'✓ Correcto.':'Revisa. '+qs[qi].h;$('feedback').style.color=ok?'#277a50':'#a33'};$('next').onclick=()=>{qi=(qi+1)%qs.length;question()};newton();dcl();constant();spring();circular();question();
