(()=>{const $=id=>document.getElementById(id),G=9.81,F=(x,d=1)=>Number(x).toFixed(d).replace(".",",");let mode="mrua",timer=null;
function plot(c,xs,ys,idx,opt={}){let q=c.getContext("2d"),w=c.width,h=c.height,L=34,R=8,T=12,B=24;q.clearRect(0,0,w,h);q.fillStyle="#fff";q.fillRect(0,0,w,h);let xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...ys),ymax=Math.max(...ys);if(xmax===xmin)xmax=xmin+1;if(ymax===ymin){ymin-=1;ymax+=1}let pad=(ymax-ymin)*.1;ymin-=pad;ymax+=pad;let X=x=>L+(x-xmin)/(xmax-xmin)*(w-L-R),Y=y=>T+(ymax-y)/(ymax-ymin)*(h-T-B);q.strokeStyle="#eee7f0";q.lineWidth=1;for(let i=0;i<=4;i++){let yy=T+i*(h-T-B)/4;q.beginPath();q.moveTo(L,yy);q.lineTo(w-R,yy);q.stroke()}if(opt.area&&idx!=null){q.fillStyle="#d92d8d22";q.beginPath();q.moveTo(X(xs[0]),Y(0));for(let i=0;i<=idx;i++)q.lineTo(X(xs[i]),Y(ys[i]));q.lineTo(X(xs[idx]),Y(0));q.closePath();q.fill()}q.strokeStyle=opt.color||"#d92d8d";q.lineWidth=2.4;q.beginPath();xs.forEach((x,i)=>i?q.lineTo(X(x),Y(ys[i])):q.moveTo(X(x),Y(ys[i])));q.stroke();if(idx!=null){idx=Math.max(0,Math.min(xs.length-1,idx));q.fillStyle="#19151d";q.beginPath();q.arc(X(xs[idx]),Y(ys[idx]),4.5,0,Math.PI*2);q.fill()}return{X,Y,xmin,xmax,ymin,ymax}}
function state(){return{x0:+$("x0").value,v0:+$("v0").value,a:mode==="mru"?0:+$("acc").value,T:+$("tmax").value}}
function setMode(m){mode=m;$("mruBtn").classList.toggle("active",m==="mru");$("mruaBtn").classList.toggle("active",m==="mrua");$("modeDesc").textContent=m==="mru"?"Velocidad constante, aceleración nula.":"Aceleración constante, velocidad que cambia.";$("acc").disabled=m==="mru";update1D(+$("timeSlider").value||0)}
function update1D(t=0){let s=state();$("timeSlider").max=s.T;$("timeMaxText").textContent=F(s.T,0)+" s";t=Math.min(s.T,Math.max(0,t));let x=s.x0+s.v0*t+.5*s.a*t*t,v=s.v0+s.a*t;$("x0Label").textContent=F(s.x0,0)+" m";$("v0Label").textContent=F(s.v0)+" m/s";$("aLabel").textContent=F(s.a)+" m/s²";$("timeText").textContent=F(t,2);$("statX").textContent=F(x)+" m";$("statV").textContent=F(v)+" m/s";$("statA").textContent=F(s.a)+" m/s²";$("statD").textContent=F(x-s.x0)+" m";$("speedVal").textContent=F(Math.abs(v))+" m/s";let z=s.a?(-s.v0/s.a):-1,dist;if(z>0&&z<t){let xx=s.x0+s.v0*z+.5*s.a*z*z;dist=Math.abs(xx-s.x0)+Math.abs(x-xx)}else dist=Math.abs(x-s.x0);$("distanceVal").textContent=F(dist)+" m";$("eqx").textContent=mode==="mru"?`x(t) = ${F(s.x0,0)} + ${F(s.v0)}t`:`x(t) = ${F(s.x0,0)} + ${F(s.v0)}t + ½(${F(s.a)})t²`;$("eqv").textContent=mode==="mru"?`v(t) = ${F(s.v0)}`:`v(t) = ${F(s.v0)} + ${F(s.a)}t`;let ts=[],xs=[],vs=[],as=[];for(let i=0;i<121;i++){let u=s.T*i/120;ts.push(u);xs.push(s.x0+s.v0*u+.5*s.a*u*u);vs.push(s.v0+s.a*u);as.push(s.a)}let idx=Math.round(t/s.T*120);plot($("xGraph"),ts,xs,idx);plot($("vGraph"),ts,vs,idx,{area:$("showArea").checked});plot($("aGraph"),ts,as,idx);drawCars(x,xs,t,s);let insight;if(Math.abs(v)<.05)insight="En este instante el móvil está detenido.";else if(s.a===0)insight="En MRU la pendiente de x(t) es constante y v(t) es horizontal.";else if(v*s.a>0)insight="Velocidad y aceleración tienen el mismo signo: la rapidez aumenta.";else insight="Velocidad y aceleración tienen signos opuestos: la rapidez disminuye.";$("insightText").textContent=insight}
function drawCars(x,xs,t,s){let mn=Math.min(...xs),mx=Math.max(...xs),pos=q=>4+78*(q-mn)/(mx-mn||1);$("carA").style.left=pos(x)+"%";let meet=$("scenario").value==="meet";$("carB").classList.toggle("hidden",!meet);$("meetControls").classList.toggle("hidden",!meet);document.querySelector(".bLabel").classList.toggle("hidden",!meet);if(meet){let bx=+$("bx0").value,bv=+$("bv0").value,bxNow=bx+bv*t;let mn2=Math.min(mn,bx,bxNow),mx2=Math.max(mx,bx,bxNow),p=q=>4+78*(q-mn2)/(mx2-mn2||1);$("carA").style.left=p(x)+"%";$("carB").style.left=p(bxNow)+"%";$("bxLabel").textContent=F(bx,0)+" m";$("bvLabel").textContent=F(bv)+" m/s";if(Math.abs(x-bxNow)<2)$("sceneName").textContent="¡Encuentro de los autos!"}
let cmp=$("compare").checked,$cc=$("carCompare"),$cl=document.querySelector(".compareLabel");$cc.classList.toggle("hidden",!cmp);$cl.classList.toggle("hidden",!cmp);if(cmp){let xc=s.x0+s.v0*t,allMin=Math.min(mn,xc,s.x0),allMax=Math.max(mx,xc,s.x0),pc=q=>4+78*(q-allMin)/(allMax-allMin||1);$("carA").style.left=pc(x)+"%";$cc.style.left=pc(xc)+"%"}}
$("mruBtn").onclick=()=>setMode("mru");$("mruaBtn").onclick=()=>setMode("mrua");
$("scenario").onchange=e=>{let p=e.target.value;$("sceneName").textContent=e.target.options[e.target.selectedIndex].text;if(p==="accelerate"){setMode("mrua");$("x0").value=0;$("v0").value=5;$("acc").value=2}if(p==="constant"){setMode("mru");$("x0").value=0;$("v0").value=8}if(p==="brake"){setMode("mrua");$("x0").value=0;$("v0").value=20;$("acc").value=-2}if(p==="reverse"){setMode("mrua");$("x0").value=20;$("v0").value=-8;$("acc").value=2}if(p==="meet"){setMode("mru");$("x0").value=-20;$("v0").value=8;$("bx0").value=80;$("bv0").value=-5} $("timeSlider").value=0;update1D(0)};
["x0","v0","acc","tmax","bx0","bv0","compare","showArea"].forEach(id=>$(id).oninput=()=>update1D(+$("timeSlider").value||0));$("timeSlider").oninput=e=>update1D(+e.target.value);
$("pause").onclick=()=>{clearInterval(timer);timer=null};$("reset").onclick=()=>{clearInterval(timer);timer=null;$("timeSlider").value=0;update1D(0)};$("play").onclick=()=>{clearInterval(timer);let rate=+$("speedSelect").value,start=Date.now()-+$("timeSlider").value*1000/rate,T=state().T;timer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=T){t=T;clearInterval(timer)}$("timeSlider").value=t;update1D(t)},30)};

/* Segments */
let segTimer=null,segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];
function segmentStates(){let x=+$("segX0").value||0,v=+$("segV0").value||0,t=0,out=[];segs.forEach((s,i)=>{let xf=x+v*s.dt+.5*s.a*s.dt*s.dt,vf=v+s.a*s.dt;out.push({i,t0:t,tf:t+s.dt,x0:x,xf,v0:v,vf,dt:s.dt,a:s.a});x=xf;v=vf;t+=s.dt});return out}
function renderSegments(){let box=$("segmentList");box.innerHTML="";segs.forEach((s,i)=>{let d=document.createElement("div");d.className="segment-row";d.innerHTML=`<div class="num">${String(i+1).padStart(2,"0")}</div><label>Duración (s)<input type="number" min=".1" step=".1" data-i="${i}" data-k="dt" value="${s.dt}"></label><label>Aceleración<input type="number" step=".1" data-i="${i}" data-k="a" value="${s.a}"></label><button data-del="${i}">×</button>`;box.appendChild(d)});box.querySelectorAll("input").forEach(el=>el.onchange=()=>{let i=+el.dataset.i,k=el.dataset.k,val=+el.value;if(k==="dt")val=Math.max(.1,val||.1);segs[i][k]=val;renderSegments()});box.querySelectorAll("[data-del]").forEach(el=>el.onclick=()=>{if(segs.length>1){segs.splice(+el.dataset.del,1);renderSegments()}});drawSegments(+$("segTime").value||0)}
function drawSegments(t=0){let S=segmentStates(),total=S.at(-1).tf;$("segTime").max=total;t=Math.min(total,Math.max(0,t));let ts=[],xs=[],vs=[],as=[];for(let i=0;i<=300;i++){let z=total*i/300,s=S.find(q=>z<=q.tf+.0001)||S.at(-1),u=Math.min(s.dt,Math.max(0,z-s.t0));ts.push(z);xs.push(s.x0+s.v0*u+.5*s.a*u*u);vs.push(s.v0+s.a*u);as.push(s.a)}let k=Math.round(t/total*300);plot($("segXGraph"),ts,xs,k);plot($("segVGraph"),ts,vs,k);plot($("segAGraph"),ts,as,k);let cs=S.find(q=>t<=q.tf+.0001)||S.at(-1),u=Math.min(cs.dt,Math.max(0,t-cs.t0));$("segNow").textContent=F(t,2);$("segCurrent").textContent=String(cs.i+1).padStart(2,"0");$("segPos").textContent=F(cs.x0+cs.v0*u+.5*cs.a*u*u);$("segVel").textContent=F(cs.v0+cs.a*u);
let currentX=cs.x0+cs.v0*u+.5*cs.a*u*u,allX=S.flatMap(s=>[s.x0,s.xf]),xmin=Math.min(...allX),xmax=Math.max(...allX),pseg=q=>5+80*(q-xmin)/(xmax-xmin||1);
$("segCar").style.left=pseg(currentX)+"%";$("segTrail").style.width=Math.max(0,pseg(currentX)-5)+"%";
let bands=$("segmentBands");bands.innerHTML="";S.forEach((s,i)=>{let b=document.createElement("div");b.className="segment-band"+(i===cs.i?" active":"");b.style.width=(100*s.dt/total)+"%";b.title=`Tramo ${i+1}: ${Math.abs(s.a)<1e-9?"MRU":"MRUA"}, a=${F(s.a)} m/s²`;bands.appendChild(b)});
let tb=$("segmentTable");tb.innerHTML="";S.forEach(s=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${String(s.i+1).padStart(2,"0")}</td><td>${Math.abs(s.a)<1e-9?"MRU":"MRUA"}</td><td>${F(s.t0,1)}</td><td>${F(s.tf,1)}</td><td>${F(s.x0,1)}</td><td>${F(s.xf,1)}</td><td>${F(s.v0,1)}</td><td>${F(s.vf,1)}</td><td>${F(s.a,1)}</td>`;tb.appendChild(tr)})}
$("addSegment").onclick=()=>{if(segs.length<10){segs.push({dt:3,a:0});renderSegments()}};$("segX0").oninput=renderSegments;$("segV0").oninput=renderSegments;$("segTime").oninput=e=>drawSegments(+e.target.value);
$("segmentPreset").onchange=e=>{if(e.target.value==="mixed")segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];if(e.target.value==="traffic")segs=[{dt:3,a:2},{dt:4,a:0},{dt:2,a:-4},{dt:3,a:0}];if(e.target.value==="turn")segs=[{dt:4,a:-3},{dt:4,a:1}];$("segTime").value=0;renderSegments()};
$("pauseSegments").onclick=()=>{clearInterval(segTimer);segTimer=null};$("resetSegments").onclick=()=>{clearInterval(segTimer);segTimer=null;$("segTime").value=0;drawSegments(0)};$("playSegments").onclick=()=>{clearInterval(segTimer);let rate=+$("segSpeed").value,total=segmentStates().at(-1).tf,start=Date.now()-+$("segTime").value*1000/rate;segTimer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=total){t=total;clearInterval(segTimer)}$("segTime").value=t;drawSegments(t)},30)};

/* Projectile */
let projTimer=null;
function pstate(){let v=+$("pv0").value,th=+$("theta").value*Math.PI/180,y0=+$("py0").value,vx=v*Math.cos(th),vy=v*Math.sin(th),tf=(vy+Math.sqrt(vy*vy+2*G*y0))/G;return{v,th,y0,vx,vy,tf}}
function updateProjectile(t=0){let s=pstate();t=Math.min(s.tf,Math.max(0,t));$("projTime").max=s.tf;$("flightLimit").textContent=F(s.tf,2)+" s";$("pv0Label").textContent=F(s.v)+" m/s";$("thetaLabel").textContent=F(s.th*180/Math.PI,0)+"°";$("py0Label").textContent=F(s.y0)+" m";let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*G*t*t),vy=s.vy-G*t;$("projTimeText").textContent=F(t,2);$("projX").textContent=F(x)+" m";$("projY").textContent=F(y)+" m";$("projVx").textContent=F(s.vx)+" m/s";$("projVy").textContent=F(vy)+" m/s";$("flight").textContent=F(s.tf,2)+" s";$("maxHeight").textContent=F(s.y0+s.vy*s.vy/(2*G),1)+" m";$("range").textContent=F(s.vx*s.tf,1)+" m";drawProjectile(s,t);let ts=[],xs=[],ys=[],vxs=[],vys=[];for(let i=0;i<121;i++){let u=s.tf*i/120;ts.push(u);xs.push(s.vx*u);ys.push(Math.max(0,s.y0+s.vy*u-.5*G*u*u));vxs.push(s.vx);vys.push(s.vy-G*u)}let k=Math.round(t/s.tf*120);plot($("pgx"),ts,xs,k);plot($("pgy"),ts,ys,k);plot($("pgvx"),ts,vxs,k);plot($("pgvy"),ts,vys,k)}
function arrow(q,x1,y1,x2,y2,color){q.strokeStyle=color;q.fillStyle=color;q.lineWidth=2;q.beginPath();q.moveTo(x1,y1);q.lineTo(x2,y2);q.stroke();let a=Math.atan2(y2-y1,x2-x1),l=8;q.beginPath();q.moveTo(x2,y2);q.lineTo(x2-l*Math.cos(a-.5),y2-l*Math.sin(a-.5));q.lineTo(x2-l*Math.cos(a+.5),y2-l*Math.sin(a+.5));q.fill()}
function drawProjectile(s,t){let c=$("projectileCanvas"),q=c.getContext("2d"),w=c.width,h=c.height,maxX=Math.max(1,s.vx*s.tf),maxY=Math.max(1,s.y0+s.vy*s.vy/(2*G)),X=x=>48+x/maxX*(w-78),Y=y=>h-36-y/maxY*(h-70);q.clearRect(0,0,w,h);q.strokeStyle="#ffffffbb";q.lineWidth=1;q.beginPath();q.moveTo(45,h-35);q.lineTo(w-20,h-35);q.moveTo(45,20);q.lineTo(45,h-35);q.stroke();q.strokeStyle="#d92d8d";q.lineWidth=3;q.beginPath();for(let i=0;i<=150;i++){let u=s.tf*i/150,x=s.vx*u,y=Math.max(0,s.y0+s.vy*u-.5*G*u*u);i?q.lineTo(X(x),Y(y)):q.moveTo(X(x),Y(y))}q.stroke();let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*G*t*t),vy=s.vy-G*t,px=X(x),py=Y(y);q.fillStyle="#19151d";q.beginPath();q.arc(px,py,6,0,Math.PI*2);q.fill();let scale=2.3;if($("showComponents").checked){arrow(q,px,py,px+s.vx*scale,py,"#7543d3");arrow(q,px,py,px,py-vy*scale,"#1b906e")}if($("showVelocity").checked)arrow(q,px,py,px+s.vx*scale,py-vy*scale,"#19151d")}
["pv0","theta","py0","showVelocity","showComponents"].forEach(id=>$(id).oninput=()=>updateProjectile(+$("projTime").value||0));$("projTime").oninput=e=>updateProjectile(+e.target.value);
$("projPreset").onchange=e=>{let p=e.target.value;if(p==="angle"){$("pv0").value=20;$("theta").value=45;$("py0").value=0}if(p==="high"){$("pv0").value=25;$("theta").value=70;$("py0").value=0}if(p==="horizontal"){$("pv0").value=20;$("theta").value=0;$("py0").value=15}if(p==="low"){$("pv0").value=30;$("theta").value=25;$("py0").value=0}$("projTime").value=0;updateProjectile(0)};
$("projReset").onclick=()=>{clearInterval(projTimer);$("projTime").value=0;updateProjectile(0)};$("launchBtn").onclick=()=>{clearInterval(projTimer);let s=pstate(),start=Date.now()-+$("projTime").value*1000;projTimer=setInterval(()=>{let t=(Date.now()-start)/1000;if(t>=s.tf){t=s.tf;clearInterval(projTimer)}$("projTime").value=t;updateProjectile(t)},30)};

/* Exercises */
const E=[
{m:"MRU · APLICACIÓN",q:"Un automóvil viaja a 72 km/h. Si en t = 0 se encuentra en x₀ = 30 m, ¿cuál será su posición 8 s después?",a:190,t:.1,u:"m",h:"Convierte primero 72 km/h a m/s.",s:"72 km/h = 20 m/s. Luego x = 30 + 20·8 = 190 m."},
{m:"MRU · ENCUENTRO",q:"Dos ciclistas están separados 150 m y avanzan uno hacia el otro con rapideces de 8 m/s y 7 m/s. ¿Cuánto tardan en encontrarse?",a:10,t:.1,u:"s",h:"Usa la rapidez relativa de acercamiento.",s:"vrel = 8 + 7 = 15 m/s. t = 150/15 = 10 s."},
{m:"MRUA · VELOCIDAD",q:"Un automóvil parte del reposo con aceleración constante de 3 m/s². ¿Qué velocidad alcanza en 6 s?",a:18,t:.1,u:"m/s",h:"Usa v = v₀ + at.",s:"v = 0 + 3·6 = 18 m/s."},
{m:"MRUA · DESPLAZAMIENTO",q:"Un móvil parte del reposo y acelera a 2 m/s² durante 5 s. ¿Qué desplazamiento realiza?",a:25,t:.1,u:"m",h:"Usa Δx = v₀t + ½at².",s:"Δx = ½·2·5² = 25 m."},
{m:"MRUA · FRENADO",q:"Un automóvil circula a 20 m/s y frena con aceleración −4 m/s². ¿Cuánto tarda en detenerse?",a:5,t:.1,u:"s",h:"Al detenerse, v = 0.",s:"0 = 20 − 4t. Por lo tanto t = 5 s."},
{m:"MRUA · CAMBIO DE SENTIDO",q:"Un móvil tiene v₀ = −8 m/s y a = +2 m/s². ¿En qué instante cambia de sentido?",a:4,t:.1,u:"s",h:"El cambio de sentido ocurre cuando v = 0.",s:"0 = −8 + 2t. Entonces t = 4 s."},
{m:"PARABÓLICO · COMPONENTES",q:"Un proyectil se lanza a 20 m/s con un ángulo de 30°. ¿Cuál es su componente vertical inicial?",a:10,t:.1,u:"m/s",h:"v₀y = v₀ sen θ.",s:"v₀y = 20 sen30° = 10 m/s."},
{m:"PARABÓLICO · COMPONENTES",q:"Un proyectil se lanza a 20 m/s con un ángulo de 60°. ¿Cuál es su componente horizontal inicial?",a:10,t:.1,u:"m/s",h:"v₀x = v₀ cos θ.",s:"v₀x = 20 cos60° = 10 m/s."},
{m:"PARABÓLICO · ALTURA",q:"Una pelota se lanza con componente vertical inicial v₀y = 14 m/s. ¿Cuánto tarda en alcanzar su altura máxima?",a:14/9.81,t:.03,u:"s",h:"En la altura máxima, vᵧ = 0.",s:"0 = 14 − 9,81t. Entonces t ≈ 1,43 s."},
{m:"CAÍDA · COMPONENTE VERTICAL",q:"Un objeto se lanza horizontalmente desde una altura de 20 m. ¿Cuánto tarda en llegar al suelo?",a:Math.sqrt(40/9.81),t:.03,u:"s",h:"La velocidad vertical inicial es cero.",s:"0 = 20 − ½·9,81·t². Resulta t ≈ 2,02 s."},
{m:"TRAMOS · VELOCIDAD",q:"Un móvil viaja a 5 m/s durante 4 s y luego acelera a 2 m/s² durante 3 s. ¿Cuál es su velocidad final?",a:11,t:.1,u:"m/s",h:"El primer tramo no modifica la velocidad.",s:"v = 5 + 2·3 = 11 m/s."},
{m:"TRAMOS · DESPLAZAMIENTO",q:"Un móvil viaja a 5 m/s durante 4 s y luego acelera desde 5 m/s a 2 m/s² durante 3 s. ¿Cuál es su desplazamiento total?",a:44,t:.1,u:"m",h:"Calcula por separado el desplazamiento de cada tramo.",s:"Tramo 1: 20 m. Tramo 2: 24 m. Total = 44 m."}
];let ei=0,solved=[];try{solved=JSON.parse(localStorage.getItem("ufro-mov-v2")||"[]")}catch(e){}
function save(){try{localStorage.setItem("ufro-mov-v2",JSON.stringify(solved))}catch(e){}let n=solved.length,p=Math.round(100*n/12);$("solvedCount").textContent=n;$("progressPct").textContent=p+"%";$("progressFill").style.width=p+"%"}
function showE(){let e=E[ei];$("exerciseMeta").textContent=`${e.m} · ${String(ei+1).padStart(2,"0")} / 12`;$("question").textContent=e.q;$("unit").textContent=e.u;$("answer").value="";$("feedback").className="";$("feedback").textContent=""}
$("check").onclick=()=>{let e=E[ei],v=parseFloat($("answer").value);if(Number.isNaN(v)){ $("feedback").className="feedback-bad";$("feedback").textContent="Ingresa una respuesta numérica.";return}let ok=Math.abs(v-e.a)<=e.t;$("feedback").className=ok?"feedback-ok":"feedback-bad";$("feedback").textContent=ok?"Correcto. La respuesta es consistente con el modelo.":"Aún no. Revisa unidades, signos y la ecuación elegida.";if(ok&&!solved.includes(ei)){solved.push(ei);save()}};$("hint").onclick=()=>{$("feedback").className="feedback-bad";$("feedback").textContent=E[ei].h};$("solution").onclick=()=>{$("feedback").className="feedback-ok";$("feedback").textContent=E[ei].s};$("next").onclick=()=>{ei=(ei+1)%12;showE()};$("prev").onclick=()=>{ei=(ei+11)%12;showE()};$("clearProgress").onclick=()=>{solved=[];save();showE()};

/* graph click exploration */
function attachGraph(canvas, slider, maxGetter, updater){canvas.addEventListener("click",e=>{let r=canvas.getBoundingClientRect(),p=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),t=p*maxGetter();slider.value=t;updater(t)})}
attachGraph($("xGraph"),$("timeSlider"),()=>state().T,update1D);attachGraph($("vGraph"),$("timeSlider"),()=>state().T,update1D);attachGraph($("aGraph"),$("timeSlider"),()=>state().T,update1D);
attachGraph($("pgx"),$("projTime"),()=>pstate().tf,updateProjectile);attachGraph($("pgy"),$("projTime"),()=>pstate().tf,updateProjectile);attachGraph($("pgvx"),$("projTime"),()=>pstate().tf,updateProjectile);attachGraph($("pgvy"),$("projTime"),()=>pstate().tf,updateProjectile);

setMode("mrua");renderSegments();updateProjectile(0);showE();save();
})();