(()=>{const $=id=>document.getElementById(id),F=(x,d=1)=>Number(x).toFixed(d).replace(".",",");let timer=null,segTimer=null,projTimer=null;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function plot(c,xs,series,idx,opt={}){let q=c.getContext("2d"),w=c.width,h=c.height,L=64,R=16,T=14,B=48;q.clearRect(0,0,w,h);q.fillStyle="#fff";q.fillRect(0,0,w,h);let all=series.flatMap(s=>s.ys),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...all),ymax=Math.max(...all);
if(opt.area){ymin=Math.min(ymin,0);ymax=Math.max(ymax,0)}
if(ymax===ymin){ymin-=1;ymax+=1}
let p=(ymax-ymin)*.12;ymin-=p;ymax+=p;let X=x=>L+(x-xmin)/(xmax-xmin||1)*(w-L-R),Y=y=>T+(ymax-y)/(ymax-ymin||1)*(h-T-B);
q.font="12px Arial";q.textBaseline="middle";
q.strokeStyle="#e7eaf4";q.lineWidth=1;
for(let i=0;i<=4;i++){let yy=T+i*(h-T-B)/4;q.beginPath();q.moveTo(L,yy);q.lineTo(w-R,yy);q.stroke();let val=ymax-i*(ymax-ymin)/4;q.fillStyle="#35406f";q.textAlign="right";q.fillText(Number(val.toFixed(1)).toString(),L-6,yy)}
for(let i=0;i<=4;i++){let xx=L+i*(w-L-R)/4,val=xmin+i*(xmax-xmin)/4;q.strokeStyle="#f0f2f8";q.beginPath();q.moveTo(xx,T);q.lineTo(xx,h-B);q.stroke();q.fillStyle="#35406f";q.textAlign="center";q.textBaseline="top";q.fillText(Number(val.toFixed(1)).toString(),xx,h-B+6)}
q.strokeStyle="#9aa3c7";q.lineWidth=1.2;q.beginPath();q.moveTo(L,h-B);q.lineTo(w-R,h-B);q.moveTo(L,T);q.lineTo(L,h-B);q.stroke();
series.forEach((s,si)=>{if(opt.area&&si===opt.areaIndex&&idx!=null){
q.save();
q.globalAlpha=.22;
q.fillStyle=s.color||"#999";
q.beginPath();
q.moveTo(X(xs[0]),Y(0));
for(let i=0;i<=idx;i++)q.lineTo(X(xs[i]),Y(s.ys[i]));
q.lineTo(X(xs[idx]),Y(0));
q.closePath();
q.fill();
q.restore();
q.save();
q.strokeStyle=s.color||"#999";
q.globalAlpha=.55;
q.lineWidth=1.5;
q.setLineDash([5,4]);
q.beginPath();
q.moveTo(X(xs[0]),Y(0));
q.lineTo(X(xs[idx]),Y(0));
q.stroke();
q.restore();
}q.strokeStyle=s.color;q.lineWidth=2.5;q.beginPath();xs.forEach((x,i)=>i?q.lineTo(X(x),Y(s.ys[i])):q.moveTo(X(x),Y(s.ys[i])));q.stroke();if(idx!=null){q.fillStyle=s.color;q.beginPath();q.arc(X(xs[idx]),Y(s.ys[idx]),4,0,Math.PI*2);q.fill()}});
q.fillStyle="#17205b";q.font="bold 12px Arial";q.textAlign="center";q.textBaseline="bottom";q.fillText(opt.xlabel||"t (s)",(L+w-R)/2,h-2);
if(opt.ylabel){q.save();q.translate(17,(T+h-B)/2);q.rotate(-Math.PI/2);q.textAlign="center";q.textBaseline="top";q.fillText(opt.ylabel,0,0);q.restore()}
return{X,Y}}
function model(){return{mx:+$("mruX0").value||0,mv:+$("mruV").value||0,x0:+$("x0").value||0,v0:+$("v0").value||0,a:+$("acc").value||0,T:+$("tmax").value||20}}
function viewMode(){return $("viewMode") ? $("viewMode").value : "both"}
function visibleSeries(mruSeries,mruaSeries){
  let mode=viewMode(), out=[];
  if(mode!=="mrua") out.push(mruSeries);
  if(mode!=="mru") out.push(mruaSeries);
  return out;
}
function updateMain(t=0){let s=model();$("timeSlider").max=s.T;t=clamp(t,0,s.T);let xm=s.mx+s.mv*t,x=s.x0+s.v0*t+.5*s.a*t*t,v=s.v0+s.a*t;$("timeText").textContent=F(t,2);$("mruStatX").textContent=F(xm)+" m";$("mruStatV").textContent=F(s.mv)+" m/s";$("statX").textContent=F(x)+" m";$("statV").textContent=F(v)+" m/s";$("statA").textContent=F(s.a)+" m/s²";$("statD").textContent=F(x-s.x0)+" m";$("speedVal").textContent=F(Math.abs(v))+" m/s";let z=s.a?(-s.v0/s.a):-1,dist;if(z>0&&z<t){let xx=s.x0+s.v0*z+.5*s.a*z*z;dist=Math.abs(xx-s.x0)+Math.abs(x-xx)}else dist=Math.abs(x-s.x0);$("distanceVal").textContent=F(dist)+" m";$("eqx").textContent=`MRUA: x(t) = ${F(s.x0,0)} + ${F(s.v0)}t + ½(${F(s.a)})t²`;$("eqv").textContent=`MRUA: v(t) = ${F(s.v0)} + ${F(s.a)}t`;
let ts=[],mX=[],mV=[],mA=[],aX=[],aV=[],aA=[];for(let i=0;i<=160;i++){let u=s.T*i/160;ts.push(u);mX.push(s.mx+s.mv*u);mV.push(s.mv);mA.push(0);aX.push(s.x0+s.v0*u+.5*s.a*u*u);aV.push(s.v0+s.a*u);aA.push(s.a)}let k=Math.round(t/s.T*160);let mode=viewMode();
let xsSeries=visibleSeries({ys:mX,color:"#2474e8"},{ys:aX,color:"#ee3f4e"});
let vsSeries=visibleSeries({ys:mV,color:"#2474e8"},{ys:aV,color:"#ee3f4e"});
let asSeries=visibleSeries({ys:mA,color:"#2474e8"},{ys:aA,color:"#ee3f4e"});
plot($("xGraph"),ts,xsSeries,k,{xlabel:"t (s)",ylabel:"x (m)"});
let vAreaIndex=(mode==="both"?1:0);
plot($("vGraph"),ts,vsSeries,k,{area:$("showArea").checked&&vAreaIndex>=0,areaIndex:vAreaIndex,xlabel:"t (s)",ylabel:"v (m/s)"});
let aAreaIndex=(mode==="both"?1:(mode==="mrua"?0:-1));
plot($("aGraph"),ts,asSeries,k,{area:$("showDeltaV").checked&&aAreaIndex>=0,areaIndex:aAreaIndex,xlabel:"t (s)",ylabel:"a (m/s²)"});
if($("deltaXReadout")){
  let dx;
  if(mode==="mru") dx=s.mv*t;
  else dx=s.v0*t+.5*s.a*t*t;
  $("deltaXReadout").textContent="Δx = "+F(dx)+" m";
}
if($("deltaVReadout")){
  let dv = mode==="mru" ? 0 : s.a*t;
  $("deltaVReadout").textContent="Δv = "+F(dv)+" m/s";
}drawMainCars(xm,x,aX,mX,t,s);let msg=s.a===0?"Ambos modelos tienen aceleración cero. Si además tienen igual velocidad, sus trayectorias coinciden.":(v*s.a<0?"El MRUA está disminuyendo su rapidez porque v y a tienen signos opuestos.":"El MRUA cambia su velocidad linealmente; el MRU conserva velocidad constante.");$("insightText").textContent=msg}
function drawMainCars(xm,x,aX,mX,t,s){let mode=viewMode(),showMRU=mode!=="mrua",showMRUA=mode!=="mru";$("carCompare").classList.toggle("hidden",!showMRU);document.querySelector(".label-mru").classList.toggle("hidden",!showMRU);$("carA").classList.toggle("hidden",!showMRUA);document.querySelector(".label-mrua").classList.toggle("hidden",!showMRUA);let vals=[];if(showMRU)vals.push(...mX);if(showMRUA)vals.push(...aX);let mn=Math.min(...vals),mx=Math.max(...vals),P=q=>3+84*(q-mn)/(mx-mn||1);$("carA").style.left=P(x)+"%";$("carCompare").style.left=P(xm)+"%";document.querySelector(".label-mrua").style.left=`calc(${P(x)}% + 38px)`;document.querySelector(".label-mru").style.left=`calc(${P(xm)}% + 38px)`;let meet=$("scenario").value==="meet";$("carB").classList.toggle("hidden",!meet);document.querySelector(".bLabel").classList.toggle("hidden",!meet);$("meetControls").classList.toggle("hidden",!meet);if(meet){let bx=+$("bx0").value||0,bv=+$("bv0").value||0,b=bx+bv*t;$("carB").style.left=P(b)+"%";document.querySelector(".bLabel").style.left=`calc(${P(b)}% + 38px)`}}
function playMain(){clearInterval(timer);let rate=+$("speedSelect").value,start=Date.now()-+$("timeSlider").value*1000/rate,T=model().T;timer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=T){t=T;clearInterval(timer)}$("timeSlider").value=t;updateMain(t)},30)}
$("play").onclick=playMain;$("pause").onclick=()=>{clearInterval(timer);timer=null};$("reset").onclick=()=>{clearInterval(timer);$("timeSlider").value=0;updateMain(0)};$("timeSlider").oninput=e=>updateMain(+e.target.value);$("speedRange").oninput=e=>{$("speedSelect").value=e.target.value};$("speedSelect").onchange=e=>{$("speedRange").value=e.target.value};
["mruX0","mruV","x0","v0","acc","tmax","showArea","showDeltaV","bx0","bv0"].forEach(id=>$(id).oninput=()=>updateMain(+$("timeSlider").value||0));
$("viewMode").onchange=()=>updateMain(+$("timeSlider").value||0);
$("viewMode").oninput=()=>updateMain(+$("timeSlider").value||0);
$("scenario").onchange=e=>{let p=e.target.value;if(p==="accelerate"){$("mruX0").value=0;$("mruV").value=20;$("x0").value=0;$("v0").value=0;$("acc").value=2}if(p==="constant"){$("mruX0").value=0;$("mruV").value=12;$("x0").value=0;$("v0").value=12;$("acc").value=0}if(p==="brake"){$("mruX0").value=0;$("mruV").value=20;$("x0").value=0;$("v0").value=20;$("acc").value=-2}if(p==="reverse"){$("mruX0").value=0;$("mruV").value=5;$("x0").value=80;$("v0").value=-10;$("acc").value=2}if(p==="meet"){$("mruX0").value=-20;$("mruV").value=8;$("x0").value=-20;$("v0").value=8;$("acc").value=0;$("bx0").value=80;$("bv0").value=-5}$("sceneName").textContent=e.target.options[e.target.selectedIndex].text;$("timeSlider").value=0;updateMain(0)};

/* Tramos */
let segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];
function segStates(){let x=+$("segX0").value||0,v=+$("segV0").value||0,t=0,out=[];segs.forEach((s,i)=>{let xf=x+v*s.dt+.5*s.a*s.dt*s.dt,vf=v+s.a*s.dt;out.push({i,t0:t,tf:t+s.dt,x0:x,xf,v0:v,vf,dt:s.dt,a:s.a});x=xf;v=vf;t+=s.dt});return out}
function renderSegs(){let box=$("segmentList");box.innerHTML="";segs.forEach((s,i)=>{let d=document.createElement("div");d.className="segment-row";d.innerHTML=`<div class="num">${String(i+1).padStart(2,"0")}</div><label>Δt<input type="number" min=".1" step=".1" data-i="${i}" data-k="dt" value="${s.dt}"></label><label>a<input type="number" step=".1" data-i="${i}" data-k="a" value="${s.a}"></label><button data-del="${i}">×</button>`;box.appendChild(d)});box.querySelectorAll("input").forEach(el=>el.onchange=()=>{let i=+el.dataset.i,k=el.dataset.k,val=+el.value;if(k==="dt")val=Math.max(.1,val||.1);segs[i][k]=val;renderSegs()});box.querySelectorAll("[data-del]").forEach(el=>el.onclick=()=>{if(segs.length>1){segs.splice(+el.dataset.del,1);renderSegs()}});drawSegs(+$("segTime").value||0)}
function drawSegs(t=0){let S=segStates(),total=S.at(-1).tf;$("segTime").max=total;t=clamp(t,0,total);let ts=[],xs=[],vs=[],as=[];for(let i=0;i<=300;i++){let z=total*i/300,s=S.find(q=>z<=q.tf+.0001)||S.at(-1),u=clamp(z-s.t0,0,s.dt);ts.push(z);xs.push(s.x0+s.v0*u+.5*s.a*u*u);vs.push(s.v0+s.a*u);as.push(s.a)}let k=Math.round(t/total*300);plot($("segXGraph"),ts,[{ys:xs,color:"#6c52dc"}],k,{xlabel:"t (s)",ylabel:"x (m)"});plot($("segVGraph"),ts,[{ys:vs,color:"#2474e8"}],k,{xlabel:"t (s)",ylabel:"v (m/s)"});plot($("segAGraph"),ts,[{ys:as,color:"#ee3f4e"}],k,{xlabel:"t (s)",ylabel:"a (m/s²)"});let cs=S.find(q=>t<=q.tf+.0001)||S.at(-1),u=clamp(t-cs.t0,0,cs.dt),cx=cs.x0+cs.v0*u+.5*cs.a*u*u;$("segNow").textContent=F(t,2)+" s";$("segCurrent").textContent=String(cs.i+1).padStart(2,"0");$("segPos").textContent=F(cx)+" m";$("segVel").textContent=F(cs.v0+cs.a*u)+" m/s";let all=S.flatMap(s=>[s.x0,s.xf]),mn=Math.min(...all),mx=Math.max(...all),P=q=>3+84*(q-mn)/(mx-mn||1);$("segCar").style.left=P(cx)+"%";let bands=$("segmentBands");bands.innerHTML="";S.forEach((s,i)=>{let b=document.createElement("div");b.className="segment-band"+(i===cs.i?" active":"");b.style.width=(100*s.dt/total)+"%";bands.appendChild(b)});let tb=$("segmentTable");tb.innerHTML="";S.forEach(s=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${String(s.i+1).padStart(2,"0")}</td><td>${Math.abs(s.a)<1e-9?"MRU":"MRUA"}</td><td>${F(s.t0,1)}</td><td>${F(s.tf,1)}</td><td>${F(s.x0,1)}</td><td>${F(s.xf,1)}</td><td>${F(s.v0,1)}</td><td>${F(s.vf,1)}</td><td>${F(s.a,1)}</td>`;tb.appendChild(tr)})}
$("addSegment").onclick=()=>{if(segs.length<10){segs.push({dt:3,a:0});renderSegs()}};$("segX0").oninput=renderSegs;$("segV0").oninput=renderSegs;$("segTime").oninput=e=>drawSegs(+e.target.value);$("segmentPreset").onchange=e=>{if(e.target.value==="mixed")segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];if(e.target.value==="traffic")segs=[{dt:3,a:2},{dt:4,a:0},{dt:2,a:-4},{dt:3,a:0}];if(e.target.value==="turn")segs=[{dt:4,a:-3},{dt:4,a:1}];$("segTime").value=0;renderSegs()};$("pauseSegments").onclick=()=>{clearInterval(segTimer)};$("resetSegments").onclick=()=>{clearInterval(segTimer);$("segTime").value=0;drawSegs(0)};$("playSegments").onclick=()=>{clearInterval(segTimer);let rate=+$("segSpeed").value,total=segStates().at(-1).tf,start=Date.now()-+$("segTime").value*1000/rate;segTimer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=total){t=total;clearInterval(segTimer)}$("segTime").value=t;drawSegs(t)},30)};

/* Projectile */
function pstate(){let v=+$("pv0").value,th=+$("theta").value*Math.PI/180,y0=+$("py0").value,g=+$("projGravity").value||9.81,vx=v*Math.cos(th),vy=v*Math.sin(th),tf=(vy+Math.sqrt(vy*vy+2*g*y0))/g;return{v,th,y0,g,vx,vy,tf}}
function arrow(q,x1,y1,x2,y2,color){q.strokeStyle=color;q.fillStyle=color;q.lineWidth=2;q.beginPath();q.moveTo(x1,y1);q.lineTo(x2,y2);q.stroke();let a=Math.atan2(y2-y1,x2-x1),l=8;q.beginPath();q.moveTo(x2,y2);q.lineTo(x2-l*Math.cos(a-.5),y2-l*Math.sin(a-.5));q.lineTo(x2-l*Math.cos(a+.5),y2-l*Math.sin(a+.5));q.fill()}
function drawProjectile(s,t){let c=$("projectileCanvas"),q=c.getContext("2d"),w=c.width,h=c.height,maxX=Math.max(1,s.vx*s.tf),maxY=Math.max(1,s.y0+s.vy*s.vy/(2*s.g)),X=x=>52+x/maxX*(w-82),Y=y=>h-38-y/maxY*(h-72);q.clearRect(0,0,w,h);q.strokeStyle="#c7d6ea";q.beginPath();q.moveTo(48,h-36);q.lineTo(w-20,h-36);q.moveTo(48,22);q.lineTo(48,h-36);q.stroke();q.strokeStyle="#6c52dc";q.lineWidth=3;q.beginPath();for(let i=0;i<=150;i++){let u=s.tf*i/150,x=s.vx*u,y=Math.max(0,s.y0+s.vy*u-.5*s.g*u*u);i?q.lineTo(X(x),Y(y)):q.moveTo(X(x),Y(y))}q.stroke();let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*s.g*t*t),vy=s.vy-s.g*t,px=X(x),py=Y(y);q.fillStyle="#ee3f4e";q.beginPath();q.arc(px,py,7,0,Math.PI*2);q.fill();let sc=2.4;if($("showComponents").checked){arrow(q,px,py,px+s.vx*sc,py,"#2474e8");arrow(q,px,py,px,py-vy*sc,"#18a05f")}if($("showVelocity").checked)arrow(q,px,py,px+s.vx*sc,py-vy*sc,"#17205b")}
function updateProj(t=0){let s=pstate();t=clamp(t,0,s.tf);$("projTime").max=s.tf;$("flightLimit").textContent=F(s.tf,2)+" s";let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*s.g*t*t),vy=s.vy-s.g*t;$("projTimeText").textContent=F(t,2);$("projX").textContent=F(x)+" m";$("projY").textContent=F(y)+" m";$("projVx").textContent=F(s.vx)+" m/s";$("projVy").textContent=F(vy)+" m/s";$("flight").textContent=F(s.tf,2)+" s";$("maxHeight").textContent=F(s.y0+s.vy*s.vy/(2*s.g),1)+" m";$("range").textContent=F(s.vx*s.tf,1)+" m";drawProjectile(s,t);let ts=[],xs=[],ys=[],vxs=[],vys=[];for(let i=0;i<=121;i++){let u=s.tf*i/121;ts.push(u);xs.push(s.vx*u);ys.push(Math.max(0,s.y0+s.vy*u-.5*s.g*u*u));vxs.push(s.vx);vys.push(s.vy-s.g*u)}let k=Math.round(t/s.tf*121);plot($("pgx"),ts,[{ys:xs,color:"#2474e8"}],k,{xlabel:"t (s)",ylabel:"x (m)"});plot($("pgy"),ts,[{ys:ys,color:"#6c52dc"}],k,{xlabel:"t (s)",ylabel:"y (m)"});plot($("pgvx"),ts,[{ys:vxs,color:"#18a05f"}],k,{xlabel:"t (s)",ylabel:"vₓ (m/s)"});plot($("pgvy"),ts,[{ys:vys,color:"#ee3f4e"}],k,{xlabel:"t (s)",ylabel:"vᵧ (m/s)"})}
["pv0","theta","py0","projGravity","showVelocity","showComponents"].forEach(id=>$(id).oninput=()=>updateProj(+$("projTime").value||0));$("projTime").oninput=e=>updateProj(+e.target.value);$("projPreset").onchange=e=>{let p=e.target.value;if(p==="angle"){$("pv0").value=20;$("theta").value=45;$("py0").value=0}if(p==="high"){$("pv0").value=25;$("theta").value=70;$("py0").value=0}if(p==="horizontal"){$("pv0").value=20;$("theta").value=0;$("py0").value=15}if(p==="low"){$("pv0").value=30;$("theta").value=25;$("py0").value=0}$("projTime").value=0;updateProj(0)};$("projReset").onclick=()=>{clearInterval(projTimer);$("projTime").value=0;updateProj(0)};$("launchBtn").onclick=()=>{clearInterval(projTimer);let s=pstate(),start=Date.now()-+$("projTime").value*1000;projTimer=setInterval(()=>{let t=(Date.now()-start)/1000;if(t>=s.tf){t=s.tf;clearInterval(projTimer)}$("projTime").value=t;updateProj(t)},30)};

/* Exercises */
const E=[
 {title:'Un auto en la carretera',category:'MRU · APLICACIÓN',prompt:'Un auto mantiene una velocidad de +72 km/h en una carretera recta. En t = 0 está en x₀ = 30 m. ¿Cuál es su posición a los 8 s?',data:['v = +72 km/h','x₀ = 30 m','t = 8 s'],unit:'m',label:'Posición final x',answer:190,tolerance:.1,hint:'Primero divide 72 entre 3,6 para obtener m/s. Luego suma a x₀ el desplazamiento vt.',wrong:n=>n===160?'Calculaste el desplazamiento (160 m). Para obtener la posición final, incorpora los 30 m iniciales.':Math.abs(n-606)<1?'Convierte km/h a m/s antes de multiplicar por un tiempo expresado en segundos.':'Revisa las unidades y recuerda que x = x₀ + vt.',success:'Correcto: x = 190 m. El desplazamiento es 160 m y la posición inicial es 30 m.',solution:['Convierte la velocidad: v = 72 / 3,6 = 20 m/s.','Calcula el desplazamiento: Δx = vt = 20 × 8 = 160 m.','Suma la posición inicial: x = 30 + 160 = 190 m.']},
 {title:'De regreso por la misma calle',category:'MRU · SIGNOS',prompt:'Una persona está en x₀ = 50 m y camina con velocidad constante v = −2 m/s durante 12 s. ¿Cuál es su desplazamiento?',data:['x₀ = 50 m','v = −2 m/s','t = 12 s'],unit:'m',label:'Desplazamiento Δx (con signo)',answer:-24,tolerance:.1,hint:'El desplazamiento es vt. Su signo indica el sentido del movimiento.',wrong:n=>n===24?'24 m es la distancia recorrida. El desplazamiento debe indicar que se movió hacia −x.':n===26?'26 m es la posición final, no el desplazamiento. Resta la posición inicial.':'Calcula Δx = v × t conservando el signo de v.',success:'Correcto: Δx = −24 m. Termina en x = 26 m y recorre una distancia de 24 m.',solution:['El desplazamiento es Δx = vt = (−2) × 12 = −24 m.','La posición final es x = 50 − 24 = 26 m.','Como no cambia de sentido, la distancia es |Δx| = 24 m.']},
 {title:'El semáforo cambia a verde',category:'MRUA · APLICACIÓN',prompt:'Un auto parte del reposo desde x₀ = 0 y mantiene una aceleración de +2,5 m/s². ¿Qué distancia recorre en los primeros 6 s?',data:['v₀ = 0 m/s','a = +2,5 m/s²','t = 6 s'],unit:'m',label:'Distancia recorrida',answer:45,tolerance:.1,hint:'Usa Δx = v₀t + ½at². Como parte del reposo, el primer término es cero.',wrong:n=>n===90?'Falta el factor ½: la velocidad final no estuvo presente durante todo el recorrido.':n===15?'15 m/s es la velocidad final. Se pide la distancia recorrida.':'Recuerda elevar el tiempo al cuadrado y multiplicar por ½.',success:'Correcto: recorre 45 m. La velocidad final es 15 m/s y la rapidez media es 7,5 m/s.',solution:['Aplica Δx = v₀t + ½at².','Sustituye: Δx = 0 + ½ × 2,5 × 6² = 45 m.','No cambia de sentido, así que la distancia es 45 m.']},
 {title:'Frenar a tiempo',category:'MRUA · FRENADO',prompt:'Un vehículo se mueve a +20 m/s. Al frenar, su aceleración es constante e igual a −4 m/s² hasta detenerse. ¿Cuánto tiempo tarda en detenerse?',data:['v₀ = +20 m/s','a = −4 m/s²','v final = 0 m/s'],unit:'s',label:'Tiempo de frenado',answer:5,tolerance:.01,hint:'En la detención v = 0. Despeja t en v = v₀ + at.',wrong:n=>n===-5?'El intervalo de tiempo es positivo. Al despejar: t = (0 − 20)/(−4).':'Usa velocidad final cero y conserva el signo negativo de la aceleración.',success:'Correcto: se detiene a los 5 s. En ese intervalo recorre 50 m.',solution:['Escribe 0 = 20 − 4t.','Despeja: t = 20 / 4 = 5 s.','La distancia de frenado es 20 × 5 − ½ × 4 × 5² = 50 m.']},
 {title:'¿Acelera o frena?',category:'MRUA · CONCEPTUAL',prompt:'En un instante, un móvil tiene velocidad v = −6 m/s y aceleración a = −2 m/s². Si esa aceleración se mantiene, ¿qué pasa con su rapidez inmediatamente después?',data:['v = −6 m/s','a = −2 m/s²'],choices:['Disminuye, porque la aceleración es negativa.','Aumenta, porque v y a tienen el mismo signo.','Se mantiene, porque la aceleración es constante.','Se hace negativa.'],answer:1,hint:'Compara los signos de v y a. Puedes calcular v un segundo después y tomar su valor absoluto.',wrong:n=>['Una aceleración negativa apunta hacia −x. Para decidir si frena, también necesitas el signo de la velocidad.','','Una aceleración constante cambia la velocidad a ritmo constante; no conserva la rapidez.','La rapidez es |v|: no puede ser negativa.'][n],success:'Correcto: un segundo después v = −8 m/s y la rapidez aumenta de 6 a 8 m/s.',solution:['La velocidad y la aceleración son negativas: tienen el mismo signo.','Un segundo después: v = −6 + (−2) × 1 = −8 m/s.','La rapidez cambia de |−6| = 6 a |−8| = 8 m/s. Por tanto, aumenta.']},
 {title:'Un encuentro en el puente',category:'DOS MÓVILES · ENCUENTRO',prompt:'Dos autos parten simultáneamente por carriles paralelos. A sale de x = 0 a +12 m/s y B de x = 100 m a −8 m/s. Ambos mantienen su velocidad. ¿En qué instante ocupan la misma posición?',data:['xA = 12t','xB = 100 − 8t','Salida simultánea'],unit:'s',label:'Instante de encuentro',answer:5,tolerance:.01,hint:'Iguala las posiciones: 12t = 100 − 8t. Al acercarse, las magnitudes de sus velocidades se suman.',wrong:n=>n===25?'Se acercan con rapidez relativa de 12 + 8 = 20 m/s. No restes las magnitudes.':'Iguala xA y xB y reúne los términos con t en el mismo lado.',success:'Correcto: se encuentran a los 5 s en x = 60 m. Sus velocidades siguen siendo diferentes.',solution:['Iguala las posiciones: 12t = 100 − 8t.','Reordena: 20t = 100, de modo que t = 5 s.','Sustituye: xA = 12 × 5 = 60 m; xB = 100 − 8 × 5 = 60 m.']},
 {title:'Volver no borra el recorrido',category:'MRUA · CAMBIO DE SENTIDO',prompt:'Un móvil parte de x₀ = 0 con v₀ = +12 m/s y a = −3 m/s² constante durante 8 s. ¿Qué distancia total recorre? Considera el cambio de sentido.',data:['v₀ = +12 m/s','a = −3 m/s²','t = 8 s'],unit:'m',label:'Distancia total recorrida',answer:48,tolerance:.1,hint:'Busca primero el instante en que v = 0. Calcula la posición en ese instante y suma las longitudes de ambos tramos.',wrong:n=>n===0?'Cero es el desplazamiento: regresa al origen. La distancia incluye la ida y la vuelta.':n===24?'24 m es solo el tramo de ida. Falta sumar el regreso.':'Divide el movimiento en dos tramos, separados por el instante de detención.',success:'Correcto: recorre 24 m de ida y 24 m de vuelta, en total 48 m. Su desplazamiento es cero.',solution:['Detención: 0 = 12 − 3t, así que t = 4 s.','Posición de retorno: x(4) = 12 × 4 − 1,5 × 4² = 24 m.','Posición final: x(8) = 12 × 8 − 1,5 × 8² = 0 m.','Distancia = |24 − 0| + |0 − 24| = 48 m; desplazamiento = 0 m.']},
 {title:'Lee el área, encuentra el cambio',category:'GRÁFICO v–t · INTERPRETACIÓN',prompt:'En una gráfica velocidad–tiempo, la velocidad aumenta linealmente desde −4 m/s en t = 0 hasta +4 m/s en t = 4 s. ¿Cuál es el desplazamiento en esos 4 s?',data:['v₀ = −4 m/s','v(4 s) = +4 m/s','a constante'],unit:'m',label:'Desplazamiento Δx (con signo)',answer:0,tolerance:.01,hint:'El área bajo el eje es negativa y el área sobre él es positiva. Suma ambas con su signo.',wrong:n=>n===8?'8 m es la distancia. Para el desplazamiento, las dos áreas tienen signos opuestos.':Math.abs(n)===4?'Incluye las dos mitades: un triángulo negativo y uno positivo.':'La velocidad media es (v₀ + vf)/2 cuando la aceleración es constante.',success:'Correcto: las áreas −4 m y +4 m se cancelan. El desplazamiento es 0 m, aunque recorrió 8 m.',solution:['La aceleración es (4 − (−4))/4 = 2 m/s²; v = 0 en t = 2 s.','Área entre 0 y 2 s: −½ × 2 × 4 = −4 m.','Área entre 2 y 4 s: +½ × 2 × 4 = +4 m.','Δx = −4 + 4 = 0 m. La distancia suma magnitudes: 8 m.']},
 {title:'El alcance de un lanzamiento',category:'PARABÓLICO · ALCANCE',prompt:'Se lanza un proyectil desde el suelo con rapidez inicial de 20 m/s y un ángulo de 45°. Sin resistencia del aire, ¿cuál es su alcance horizontal?',data:['v₀ = 20 m/s','θ = 45°','y₀ = 0 m','g = 9,81 m/s²'],unit:'m',label:'Alcance horizontal',answer:40.77,tolerance:.1,hint:'Calcula v₀ₓ y el tiempo de vuelo. Luego usa R = v₀ₓtᵥ.',wrong:n=>Math.abs(n-20.39)<.2?'Ese valor se relaciona con la altura, no con el alcance. Usa el tiempo de vuelo completo.':'Descompón la velocidad inicial y recuerda que el proyectil sube y baja.',success:'Correcto: el tiempo de vuelo es 2,88 s y el alcance es aproximadamente 40,8 m.',solution:['v₀ₓ = 20 cos 45° = 14,14 m/s y v₀ᵧ = 14,14 m/s.','tᵥ = 2v₀ᵧ/g = 2,88 s.','R = v₀ₓtᵥ = 40,77 m.']},
 {title:'Desde una plataforma',category:'PARABÓLICO · LANZAMIENTO HORIZONTAL',prompt:'Una pelota se lanza horizontalmente a 18 m/s desde una plataforma de 15 m de altura. ¿Cuánto tarda en llegar al suelo?',data:['v₀ₓ = 18 m/s','v₀ᵧ = 0 m/s','y₀ = 15 m'],unit:'s',label:'Tiempo de caída',answer:1.75,tolerance:.02,hint:'El tiempo se obtiene solo desde el movimiento vertical: 0 = y₀ − ½gt².',wrong:n=>Math.abs(n-.83)<.1?'La velocidad horizontal no determina el tiempo de caída. Usa la ecuación vertical.':'Aísla t² en 15 = ½gt² y toma la raíz positiva.',success:'Correcto: tarda aproximadamente 1,75 s. En ese tiempo avanza unos 31,5 m.',solution:['En vertical: 0 = 15 − ½(9,81)t².','t = √(2 × 15 / 9,81) = 1,75 s.','El alcance sería x = 18 × 1,75 ≈ 31,5 m.']},
 {title:'¿Qué ocurre en la cima?',category:'PARABÓLICO · CONCEPTUAL',prompt:'Un proyectil alcanza su altura máxima. ¿Cuál afirmación describe correctamente ese instante?',data:['Sin resistencia del aire','Eje +y hacia arriba'],choices:['La velocidad total y la aceleración son cero.','vᵧ = 0, pero vₓ se mantiene y aᵧ = −g.','vₓ = 0 y vᵧ conserva su valor inicial.','La aceleración cambia de signo para hacerlo descender.'],answer:1,hint:'La gravedad actúa durante toda la trayectoria. Solo una componente de la velocidad se anula en la cima.',wrong:n=>['Si el lanzamiento es oblicuo, vₓ sigue presente y la gravedad no se anula.','','La componente horizontal permanece constante; la vertical llega a cero.','La aceleración apunta hacia abajo durante toda la trayectoria.'][n],success:'Correcto: en la cima vᵧ = 0, pero vₓ ≠ 0 y la aceleración continúa siendo −g ĵ.',solution:['vₓ = v₀ cos θ permanece constante.','En la altura máxima, vᵧ = 0 solo instantáneamente.','La aceleración es siempre a⃗ = −g ĵ.']},
 {title:'Lanzamiento desde altura',category:'PARABÓLICO · INTEGRACIÓN',prompt:'Un objeto se lanza desde 5 m de altura con rapidez de 10 m/s a 45°. ¿Cuál es su alcance horizontal hasta tocar el suelo?',data:['v₀ = 10 m/s','θ = 45°','y₀ = 5 m','g = 9,81 m/s²'],unit:'m',label:'Alcance horizontal',answer:13.87,tolerance:.1,hint:'Resuelve 0 = 5 + v₀ sen(45°)t − ½gt² y conserva la raíz positiva.',wrong:n=>Math.abs(n-10.19)<.2?'Ese resultado supone salida y llegada a la misma altura. Aquí el suelo está 5 m más abajo.':'Incluye la altura inicial en la ecuación vertical.',success:'Correcto: el tiempo de vuelo es aproximadamente 1,96 s y el alcance es 13,9 m.',solution:['v₀ₓ = v₀ᵧ = 10/√2 = 7,07 m/s.','La raíz positiva de 0 = 5 + 7,07t − 4,905t² es t = 1,96 s.','R = 7,07 × 1,96 = 13,87 m.']},
 {title:'Un punto en el borde',category:'MCU · RAPIDEZ TANGENCIAL',prompt:'Una rueda de radio 0,75 m gira con velocidad angular constante ω = 4,0 rad/s. ¿Cuál es la rapidez tangencial de un punto de su borde?',data:['R = 0,75 m','ω = 4,0 rad/s'],unit:'m/s',label:'Rapidez tangencial v',answer:3,tolerance:.01,hint:'Relaciona las magnitudes lineal y angular mediante v = Rω.',wrong:n=>Math.abs(n-4.75)<.05?'No debes sumar el radio y la velocidad angular.':'Multiplica el radio por la magnitud de la velocidad angular.',success:'Correcto: el punto se mueve con rapidez tangencial de 3,0 m/s.',solution:['Usa v = R|ω|.','Sustituye: v = 0,75 × 4,0.','Por tanto, v = 3,0 m/s.']},
 {title:'Hacia el centro',category:'MCU · ACELERACIÓN CENTRÍPETA',prompt:'Un móvil describe una circunferencia de radio 2,0 m con ω = 3,0 rad/s. ¿Cuál es la magnitud de su aceleración centrípeta?',data:['R = 2,0 m','ω = 3,0 rad/s'],unit:'m/s²',label:'Aceleración centrípeta aᶜ',answer:18,tolerance:.05,hint:'Usa aᶜ = Rω². Recuerda elevar ω al cuadrado.',wrong:n=>Math.abs(n-6)<.1?'Ese resultado corresponde a Rω; falta elevar ω al cuadrado.':'Revisa aᶜ = Rω² y las unidades.',success:'Correcto: aᶜ = 18,0 m/s² y apunta hacia el centro.',solution:['La expresión angular es aᶜ = Rω².','Sustituye: aᶜ = 2,0 × (3,0)².','Entonces aᶜ = 18,0 m/s², dirigida radialmente hacia el centro.']},
 {title:'Tiempo de una vuelta',category:'MCU · PERÍODO',prompt:'Un disco gira con velocidad angular constante ω = π rad/s. ¿Cuánto tarda en completar una vuelta?',data:['ω = π rad/s','Una vuelta = 2π rad'],unit:'s',label:'Período T',answer:2,tolerance:.01,hint:'El período se obtiene con T = 2π/|ω|.',wrong:n=>Math.abs(n-Math.PI)<.05?'π es la velocidad angular dada, no el período.':'Divide el ángulo de una vuelta, 2π rad, por la velocidad angular.',success:'Correcto: completa una vuelta cada 2,0 s.',solution:['Una vuelta corresponde a Δθ = 2π rad.','Usa T = 2π/|ω|.','T = 2π/π = 2,0 s.']},
 {title:'Un disco que acelera',category:'MCUA · POSICIÓN ANGULAR',prompt:'Un disco parte desde θ₀ = 0,50 rad con ω₀ = 2,0 rad/s y α = 1,0 rad/s². ¿Cuál es su posición angular a los 3,0 s?',data:['θ₀ = 0,50 rad','ω₀ = 2,0 rad/s','α = 1,0 rad/s²','t = 3,0 s'],unit:'rad',label:'Posición angular θ',answer:11,tolerance:.02,hint:'Usa θ = θ₀ + ω₀t + ½αt².',wrong:n=>Math.abs(n-15.5)<.1?'Falta el factor ½ en el término de aceleración angular.':'Incluye θ₀, el término ω₀t y el término ½αt².',success:'Correcto: la posición angular es 11,0 rad.',solution:['Escribe θ = θ₀ + ω₀t + ½αt².','Sustituye: θ = 0,50 + 2,0 × 3,0 + ½ × 1,0 × (3,0)².','θ = 0,50 + 6,0 + 4,50 = 11,0 rad.']},
 {title:'Rotación que pierde rapidez',category:'MCUA · VELOCIDAD ANGULAR',prompt:'Un volante gira con ω₀ = 5,0 rad/s y tiene α = −1,5 rad/s². ¿Cuál es su velocidad angular después de 2,0 s?',data:['ω₀ = 5,0 rad/s','α = −1,5 rad/s²','t = 2,0 s'],unit:'rad/s',label:'Velocidad angular ω',answer:2,tolerance:.01,hint:'Aplica ω = ω₀ + αt conservando el signo de α.',wrong:n=>Math.abs(n-8)<.05?'La aceleración angular es negativa, por lo que ω disminuye.':'Suma algebraicamente αt a ω₀.',success:'Correcto: ω = 2,0 rad/s; todavía gira en el sentido positivo.',solution:['Usa ω = ω₀ + αt.','Sustituye: ω = 5,0 + (−1,5) × 2,0.','ω = 2,0 rad/s. Como sigue siendo positiva, aún no cambia de sentido.']},
 {title:'Encuentro sobre la circunferencia',category:'MCU · DOS MÓVILES',prompt:'Dos móviles recorren la misma circunferencia. A parte desde θ₀A = 0 rad con ωA = 2,0 rad/s; B parte desde θ₀B = π rad con ωB = 1,0 rad/s. ¿Cuándo ocurre el primer encuentro?',data:['θA = 2t','θB = π + t','Mismo radio'],unit:'s',label:'Primer instante de encuentro',answer:Math.PI,tolerance:.02,hint:'En el primer encuentro puedes igualar θA = θB: 2t = π + t.',wrong:n=>Math.abs(n-2*Math.PI)<.05?'Ese tiempo corresponde a una vuelta completa, pero se encuentran antes.':'Iguala las posiciones angulares y despeja t.',success:'Correcto: el primer encuentro ocurre en t = π s, aproximadamente 3,14 s.',solution:['Iguala las posiciones angulares: 2t = π + t.','Resta t en ambos lados: t = π s.','Numéricamente, t ≈ 3,14 s. Como tienen el mismo radio, la coincidencia angular es un encuentro espacial.']}
];let ei=0,solved=[];try{solved=JSON.parse(localStorage.getItem("ufro-mov-v6")||"[]")}catch(e){}
const TOTAL=E.length;
function save(){try{localStorage.setItem("ufro-mov-v6",JSON.stringify(solved))}catch(e){}let n=solved.length,p=Math.round(100*n/TOTAL);$("solvedCount").textContent=n;$("progressPct").textContent=p+"%";$("progressFill").style.width=p+"%"}
function showE(){
  let e=E[ei];
  $("exerciseMeta").textContent=`${e.category} · ${String(ei+1).padStart(2,"0")} / ${TOTAL}`;
  $("question").textContent=e.prompt;
  $("exerciseTitle").textContent=e.title||"";
  $("exerciseData").innerHTML=(e.data||[]).map(x=>`<span>${x}</span>`).join("");
  $("feedback").className="";
  $("feedback").textContent="";
  $("choices").innerHTML="";
  $("answer").value="";
  if(e.choices){
    $("numericAnswer").classList.add("hidden");
    $("choices").classList.remove("hidden");
    e.choices.forEach((c,idx)=>{
      let b=document.createElement("button");
      b.type="button"; b.className="choice-btn"; b.textContent=c; b.dataset.choice=idx;
      b.onclick=()=>{$("choices").querySelectorAll("button").forEach(x=>x.classList.remove("selected"));b.classList.add("selected")};
      $("choices").appendChild(b);
    });
  }else{
    $("choices").classList.add("hidden");
    $("numericAnswer").classList.remove("hidden");
    $("unit").textContent=e.unit||"";
  }
}
$("check").onclick=()=>{
  let e=E[ei],ok=false;
  if(e.choices){
    let sel=$("choices").querySelector(".selected");
    if(!sel){$("feedback").className="feedback-bad";$("feedback").textContent="Selecciona una alternativa.";return}
    let n=+sel.dataset.choice; ok=n===e.answer;
    $("feedback").className=ok?"feedback-ok":"feedback-bad";
    $("feedback").textContent=ok?e.success:(e.wrong?e.wrong(n):"Aún no. Revisa el concepto.");
  }else{
    let v=parseFloat($("answer").value);
    if(Number.isNaN(v)){$("feedback").className="feedback-bad";$("feedback").textContent="Ingresa una respuesta numérica.";return}
    ok=Math.abs(v-e.answer)<=e.tolerance;
    $("feedback").className=ok?"feedback-ok":"feedback-bad";
    $("feedback").textContent=ok?e.success:(e.wrong?e.wrong(v):"Aún no. Revisa unidades, signos y la ecuación elegida.");
  }
  if(ok&&!solved.includes(ei)){solved.push(ei);save()}
};
$("hint").onclick=()=>{$("feedback").className="feedback-bad";$("feedback").textContent=E[ei].hint||""};
$("solution").onclick=()=>{$("feedback").className="feedback-ok";$("feedback").textContent=(E[ei].solution||[]).join(" ")};
$("next").onclick=()=>{ei=(ei+1)%TOTAL;showE()};
$("prev").onclick=()=>{ei=(ei+TOTAL-1)%TOTAL;showE()};
$("clearProgress").onclick=()=>{solved=[];save();showE()};

/* graph click */
function attach(canvas,slider,maxFn,fn){canvas.addEventListener("click",e=>{let r=canvas.getBoundingClientRect(),p=clamp((e.clientX-r.left)/r.width,0,1),t=p*maxFn();slider.value=t;fn(t)})}
attach($("xGraph"),$("timeSlider"),()=>model().T,updateMain);attach($("vGraph"),$("timeSlider"),()=>model().T,updateMain);attach($("aGraph"),$("timeSlider"),()=>model().T,updateMain);
attach($("pgx"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgy"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgvx"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgvy"),$("projTime"),()=>pstate().tf,updateProj);

updateMain(0);renderSegs();updateProj(0);showE();save();
})();