(()=>{const $=id=>document.getElementById(id),G=9.81,F=(x,d=1)=>Number(x).toFixed(d).replace(".",",");let timer=null,segTimer=null,projTimer=null;
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function plot(c,xs,series,idx,opt={}){let q=c.getContext("2d"),w=c.width,h=c.height,L=42,R=10,T=14,B=28;q.clearRect(0,0,w,h);q.fillStyle="#fff";q.fillRect(0,0,w,h);let all=series.flatMap(s=>s.ys),xmin=Math.min(...xs),xmax=Math.max(...xs),ymin=Math.min(...all),ymax=Math.max(...all);if(ymax===ymin){ymin-=1;ymax+=1}let p=(ymax-ymin)*.12;ymin-=p;ymax+=p;let X=x=>L+(x-xmin)/(xmax-xmin||1)*(w-L-R),Y=y=>T+(ymax-y)/(ymax-ymin||1)*(h-T-B);q.strokeStyle="#e7eaf4";q.lineWidth=1;for(let i=0;i<=4;i++){let yy=T+i*(h-T-B)/4;q.beginPath();q.moveTo(L,yy);q.lineTo(w-R,yy);q.stroke()}q.strokeStyle="#9aa3c7";q.beginPath();q.moveTo(L,h-B);q.lineTo(w-R,h-B);q.moveTo(L,T);q.lineTo(L,h-B);q.stroke();series.forEach((s,si)=>{if(opt.area&&si===opt.areaIndex&&idx!=null){q.fillStyle=(s.color||"#999")+"22";q.beginPath();q.moveTo(X(xs[0]),Y(0));for(let i=0;i<=idx;i++)q.lineTo(X(xs[i]),Y(s.ys[i]));q.lineTo(X(xs[idx]),Y(0));q.closePath();q.fill()}q.strokeStyle=s.color;q.lineWidth=2.5;q.beginPath();xs.forEach((x,i)=>i?q.lineTo(X(x),Y(s.ys[i])):q.moveTo(X(x),Y(s.ys[i])));q.stroke();if(idx!=null){q.fillStyle=s.color;q.beginPath();q.arc(X(xs[idx]),Y(s.ys[idx]),4,0,Math.PI*2);q.fill()}});return{X,Y}}
function model(){return{mx:+$("mruX0").value||0,mv:+$("mruV").value||0,x0:+$("x0").value||0,v0:+$("v0").value||0,a:+$("acc").value||0,T:+$("tmax").value||20}}
function updateMain(t=0){let s=model();$("timeSlider").max=s.T;t=clamp(t,0,s.T);let xm=s.mx+s.mv*t,x=s.x0+s.v0*t+.5*s.a*t*t,v=s.v0+s.a*t;$("timeText").textContent=F(t,2);$("mruStatX").textContent=F(xm)+" m";$("mruStatV").textContent=F(s.mv)+" m/s";$("statX").textContent=F(x)+" m";$("statV").textContent=F(v)+" m/s";$("statA").textContent=F(s.a)+" m/s²";$("statD").textContent=F(x-s.x0)+" m";$("speedVal").textContent=F(Math.abs(v))+" m/s";let z=s.a?(-s.v0/s.a):-1,dist;if(z>0&&z<t){let xx=s.x0+s.v0*z+.5*s.a*z*z;dist=Math.abs(xx-s.x0)+Math.abs(x-xx)}else dist=Math.abs(x-s.x0);$("distanceVal").textContent=F(dist)+" m";$("eqx").textContent=`MRUA: x(t) = ${F(s.x0,0)} + ${F(s.v0)}t + ½(${F(s.a)})t²`;$("eqv").textContent=`MRUA: v(t) = ${F(s.v0)} + ${F(s.a)}t`;
let ts=[],mX=[],mV=[],mA=[],aX=[],aV=[],aA=[];for(let i=0;i<=160;i++){let u=s.T*i/160;ts.push(u);mX.push(s.mx+s.mv*u);mV.push(s.mv);mA.push(0);aX.push(s.x0+s.v0*u+.5*s.a*u*u);aV.push(s.v0+s.a*u);aA.push(s.a)}let k=Math.round(t/s.T*160);plot($("xGraph"),ts,[{ys:mX,color:"#2474e8"},{ys:aX,color:"#ee3f4e"}],k);plot($("vGraph"),ts,[{ys:mV,color:"#2474e8"},{ys:aV,color:"#ee3f4e"}],k,{area:$("showArea").checked,areaIndex:1});plot($("aGraph"),ts,[{ys:mA,color:"#2474e8"},{ys:aA,color:"#ee3f4e"}],k);drawMainCars(xm,x,aX,mX,t,s);let msg=s.a===0?"Ambos modelos tienen aceleración cero. Si además tienen igual velocidad, sus trayectorias coinciden.":(v*s.a<0?"El MRUA está disminuyendo su rapidez porque v y a tienen signos opuestos.":"El MRUA cambia su velocidad linealmente; el MRU conserva velocidad constante.");$("insightText").textContent=msg}
function drawMainCars(xm,x,aX,mX,t,s){let show=$("compare").checked;$("carCompare").classList.toggle("hidden",!show);document.querySelector(".label-mru").classList.toggle("hidden",!show);let mn=Math.min(...aX,...mX),mx=Math.max(...aX,...mX),P=q=>3+84*(q-mn)/(mx-mn||1);$("carA").style.left=P(x)+"%";$("carCompare").style.left=P(xm)+"%";document.querySelector(".label-mrua").style.left=`calc(${P(x)}% + 38px)`;document.querySelector(".label-mru").style.left=`calc(${P(xm)}% + 38px)`;let meet=$("scenario").value==="meet";$("carB").classList.toggle("hidden",!meet);document.querySelector(".bLabel").classList.toggle("hidden",!meet);$("meetControls").classList.toggle("hidden",!meet);if(meet){let bx=+$("bx0").value||0,bv=+$("bv0").value||0,b=bx+bv*t;$("carB").style.left=P(b)+"%";document.querySelector(".bLabel").style.left=`calc(${P(b)}% + 38px)`}}
function playMain(){clearInterval(timer);let rate=+$("speedSelect").value,start=Date.now()-+$("timeSlider").value*1000/rate,T=model().T;timer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=T){t=T;clearInterval(timer)}$("timeSlider").value=t;updateMain(t)},30)}
$("play").onclick=playMain;$("pause").onclick=()=>{clearInterval(timer);timer=null};$("reset").onclick=()=>{clearInterval(timer);$("timeSlider").value=0;updateMain(0)};$("timeSlider").oninput=e=>updateMain(+e.target.value);$("speedRange").oninput=e=>{$("speedSelect").value=e.target.value};$("speedSelect").onchange=e=>{$("speedRange").value=e.target.value};
["mruX0","mruV","x0","v0","acc","tmax","compare","showArea","bx0","bv0"].forEach(id=>$(id).oninput=()=>updateMain(+$("timeSlider").value||0));
$("scenario").onchange=e=>{let p=e.target.value;if(p==="accelerate"){$("mruX0").value=0;$("mruV").value=20;$("x0").value=0;$("v0").value=0;$("acc").value=2}if(p==="constant"){$("mruX0").value=0;$("mruV").value=12;$("x0").value=0;$("v0").value=12;$("acc").value=0}if(p==="brake"){$("mruX0").value=0;$("mruV").value=20;$("x0").value=0;$("v0").value=20;$("acc").value=-2}if(p==="reverse"){$("mruX0").value=0;$("mruV").value=5;$("x0").value=80;$("v0").value=-10;$("acc").value=2}if(p==="meet"){$("mruX0").value=-20;$("mruV").value=8;$("x0").value=-20;$("v0").value=8;$("acc").value=0;$("bx0").value=80;$("bv0").value=-5}$("sceneName").textContent=e.target.options[e.target.selectedIndex].text;$("timeSlider").value=0;updateMain(0)};

/* Tramos */
let segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];
function segStates(){let x=+$("segX0").value||0,v=+$("segV0").value||0,t=0,out=[];segs.forEach((s,i)=>{let xf=x+v*s.dt+.5*s.a*s.dt*s.dt,vf=v+s.a*s.dt;out.push({i,t0:t,tf:t+s.dt,x0:x,xf,v0:v,vf,dt:s.dt,a:s.a});x=xf;v=vf;t+=s.dt});return out}
function renderSegs(){let box=$("segmentList");box.innerHTML="";segs.forEach((s,i)=>{let d=document.createElement("div");d.className="segment-row";d.innerHTML=`<div class="num">${String(i+1).padStart(2,"0")}</div><label>Δt<input type="number" min=".1" step=".1" data-i="${i}" data-k="dt" value="${s.dt}"></label><label>a<input type="number" step=".1" data-i="${i}" data-k="a" value="${s.a}"></label><button data-del="${i}">×</button>`;box.appendChild(d)});box.querySelectorAll("input").forEach(el=>el.onchange=()=>{let i=+el.dataset.i,k=el.dataset.k,val=+el.value;if(k==="dt")val=Math.max(.1,val||.1);segs[i][k]=val;renderSegs()});box.querySelectorAll("[data-del]").forEach(el=>el.onclick=()=>{if(segs.length>1){segs.splice(+el.dataset.del,1);renderSegs()}});drawSegs(+$("segTime").value||0)}
function drawSegs(t=0){let S=segStates(),total=S.at(-1).tf;$("segTime").max=total;t=clamp(t,0,total);let ts=[],xs=[],vs=[],as=[];for(let i=0;i<=300;i++){let z=total*i/300,s=S.find(q=>z<=q.tf+.0001)||S.at(-1),u=clamp(z-s.t0,0,s.dt);ts.push(z);xs.push(s.x0+s.v0*u+.5*s.a*u*u);vs.push(s.v0+s.a*u);as.push(s.a)}let k=Math.round(t/total*300);plot($("segXGraph"),ts,[{ys:xs,color:"#6c52dc"}],k);plot($("segVGraph"),ts,[{ys:vs,color:"#2474e8"}],k);plot($("segAGraph"),ts,[{ys:as,color:"#ee3f4e"}],k);let cs=S.find(q=>t<=q.tf+.0001)||S.at(-1),u=clamp(t-cs.t0,0,cs.dt),cx=cs.x0+cs.v0*u+.5*cs.a*u*u;$("segNow").textContent=F(t,2)+" s";$("segCurrent").textContent=String(cs.i+1).padStart(2,"0");$("segPos").textContent=F(cx)+" m";$("segVel").textContent=F(cs.v0+cs.a*u)+" m/s";let all=S.flatMap(s=>[s.x0,s.xf]),mn=Math.min(...all),mx=Math.max(...all),P=q=>3+84*(q-mn)/(mx-mn||1);$("segCar").style.left=P(cx)+"%";let bands=$("segmentBands");bands.innerHTML="";S.forEach((s,i)=>{let b=document.createElement("div");b.className="segment-band"+(i===cs.i?" active":"");b.style.width=(100*s.dt/total)+"%";bands.appendChild(b)});let tb=$("segmentTable");tb.innerHTML="";S.forEach(s=>{let tr=document.createElement("tr");tr.innerHTML=`<td>${String(s.i+1).padStart(2,"0")}</td><td>${Math.abs(s.a)<1e-9?"MRU":"MRUA"}</td><td>${F(s.t0,1)}</td><td>${F(s.tf,1)}</td><td>${F(s.x0,1)}</td><td>${F(s.xf,1)}</td><td>${F(s.v0,1)}</td><td>${F(s.vf,1)}</td><td>${F(s.a,1)}</td>`;tb.appendChild(tr)})}
$("addSegment").onclick=()=>{if(segs.length<10){segs.push({dt:3,a:0});renderSegs()}};$("segX0").oninput=renderSegs;$("segV0").oninput=renderSegs;$("segTime").oninput=e=>drawSegs(+e.target.value);$("segmentPreset").onchange=e=>{if(e.target.value==="mixed")segs=[{dt:4,a:0},{dt:3,a:2},{dt:4,a:-2}];if(e.target.value==="traffic")segs=[{dt:3,a:2},{dt:4,a:0},{dt:2,a:-4},{dt:3,a:0}];if(e.target.value==="turn")segs=[{dt:4,a:-3},{dt:4,a:1}];$("segTime").value=0;renderSegs()};$("pauseSegments").onclick=()=>{clearInterval(segTimer)};$("resetSegments").onclick=()=>{clearInterval(segTimer);$("segTime").value=0;drawSegs(0)};$("playSegments").onclick=()=>{clearInterval(segTimer);let rate=+$("segSpeed").value,total=segStates().at(-1).tf,start=Date.now()-+$("segTime").value*1000/rate;segTimer=setInterval(()=>{let t=(Date.now()-start)/1000*rate;if(t>=total){t=total;clearInterval(segTimer)}$("segTime").value=t;drawSegs(t)},30)};

/* Projectile */
function pstate(){let v=+$("pv0").value,th=+$("theta").value*Math.PI/180,y0=+$("py0").value,vx=v*Math.cos(th),vy=v*Math.sin(th),tf=(vy+Math.sqrt(vy*vy+2*G*y0))/G;return{v,th,y0,vx,vy,tf}}
function arrow(q,x1,y1,x2,y2,color){q.strokeStyle=color;q.fillStyle=color;q.lineWidth=2;q.beginPath();q.moveTo(x1,y1);q.lineTo(x2,y2);q.stroke();let a=Math.atan2(y2-y1,x2-x1),l=8;q.beginPath();q.moveTo(x2,y2);q.lineTo(x2-l*Math.cos(a-.5),y2-l*Math.sin(a-.5));q.lineTo(x2-l*Math.cos(a+.5),y2-l*Math.sin(a+.5));q.fill()}
function drawProjectile(s,t){let c=$("projectileCanvas"),q=c.getContext("2d"),w=c.width,h=c.height,maxX=Math.max(1,s.vx*s.tf),maxY=Math.max(1,s.y0+s.vy*s.vy/(2*G)),X=x=>52+x/maxX*(w-82),Y=y=>h-38-y/maxY*(h-72);q.clearRect(0,0,w,h);q.strokeStyle="#c7d6ea";q.beginPath();q.moveTo(48,h-36);q.lineTo(w-20,h-36);q.moveTo(48,22);q.lineTo(48,h-36);q.stroke();q.strokeStyle="#6c52dc";q.lineWidth=3;q.beginPath();for(let i=0;i<=150;i++){let u=s.tf*i/150,x=s.vx*u,y=Math.max(0,s.y0+s.vy*u-.5*G*u*u);i?q.lineTo(X(x),Y(y)):q.moveTo(X(x),Y(y))}q.stroke();let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*G*t*t),vy=s.vy-G*t,px=X(x),py=Y(y);q.fillStyle="#ee3f4e";q.beginPath();q.arc(px,py,7,0,Math.PI*2);q.fill();let sc=2.4;if($("showComponents").checked){arrow(q,px,py,px+s.vx*sc,py,"#2474e8");arrow(q,px,py,px,py-vy*sc,"#18a05f")}if($("showVelocity").checked)arrow(q,px,py,px+s.vx*sc,py-vy*sc,"#17205b")}
function updateProj(t=0){let s=pstate();t=clamp(t,0,s.tf);$("projTime").max=s.tf;$("flightLimit").textContent=F(s.tf,2)+" s";$("pv0Label").textContent=F(s.v)+" m/s";$("thetaLabel").textContent=F(s.th*180/Math.PI,0)+"°";$("py0Label").textContent=F(s.y0)+" m";let x=s.vx*t,y=Math.max(0,s.y0+s.vy*t-.5*G*t*t),vy=s.vy-G*t;$("projTimeText").textContent=F(t,2);$("projX").textContent=F(x)+" m";$("projY").textContent=F(y)+" m";$("projVx").textContent=F(s.vx)+" m/s";$("projVy").textContent=F(vy)+" m/s";$("flight").textContent=F(s.tf,2)+" s";$("maxHeight").textContent=F(s.y0+s.vy*s.vy/(2*G),1)+" m";$("range").textContent=F(s.vx*s.tf,1)+" m";drawProjectile(s,t);let ts=[],xs=[],ys=[],vxs=[],vys=[];for(let i=0;i<=121;i++){let u=s.tf*i/121;ts.push(u);xs.push(s.vx*u);ys.push(Math.max(0,s.y0+s.vy*u-.5*G*u*u));vxs.push(s.vx);vys.push(s.vy-G*u)}let k=Math.round(t/s.tf*121);plot($("pgx"),ts,[{ys:xs,color:"#2474e8"}],k);plot($("pgy"),ts,[{ys:ys,color:"#6c52dc"}],k);plot($("pgvx"),ts,[{ys:vxs,color:"#18a05f"}],k);plot($("pgvy"),ts,[{ys:vys,color:"#ee3f4e"}],k)}
["pv0","theta","py0","showVelocity","showComponents"].forEach(id=>$(id).oninput=()=>updateProj(+$("projTime").value||0));$("projTime").oninput=e=>updateProj(+e.target.value);$("projPreset").onchange=e=>{let p=e.target.value;if(p==="angle"){$("pv0").value=20;$("theta").value=45;$("py0").value=0}if(p==="high"){$("pv0").value=25;$("theta").value=70;$("py0").value=0}if(p==="horizontal"){$("pv0").value=20;$("theta").value=0;$("py0").value=15}if(p==="low"){$("pv0").value=30;$("theta").value=25;$("py0").value=0}$("projTime").value=0;updateProj(0)};$("projReset").onclick=()=>{clearInterval(projTimer);$("projTime").value=0;updateProj(0)};$("launchBtn").onclick=()=>{clearInterval(projTimer);let s=pstate(),start=Date.now()-+$("projTime").value*1000;projTimer=setInterval(()=>{let t=(Date.now()-start)/1000;if(t>=s.tf){t=s.tf;clearInterval(projTimer)}$("projTime").value=t;updateProj(t)},30)};

/* Exercises */
const E=[
{m:"MRU · APLICACIÓN",q:"Un automóvil viaja a 72 km/h. Si en t = 0 se encuentra en x₀ = 30 m, ¿cuál será su posición 8 s después?",a:190,t:.1,u:"m",h:"Convierte primero 72 km/h a m/s.",s:"72 km/h = 20 m/s. Luego x = 30 + 20·8 = 190 m."},
{m:"MRU · ENCUENTRO",q:"Dos ciclistas están separados 150 m y avanzan uno hacia el otro con rapideces de 8 m/s y 7 m/s. ¿Cuánto tardan en encontrarse?",a:10,t:.1,u:"s",h:"Usa la rapidez relativa de acercamiento.",s:"vrel = 8 + 7 = 15 m/s. t = 150/15 = 10 s."},
{m:"MRUA · VELOCIDAD",q:"Un automóvil parte del reposo con aceleración constante de 3 m/s². ¿Qué velocidad alcanza en 6 s?",a:18,t:.1,u:"m/s",h:"Usa v = v₀ + at.",s:"v = 0 + 3·6 = 18 m/s."},
{m:"MRUA · DESPLAZAMIENTO",q:"Un móvil parte del reposo y acelera a 2 m/s² durante 5 s. ¿Qué desplazamiento realiza?",a:25,t:.1,u:"m",h:"Usa Δx = v₀t + ½at².",s:"Δx = ½·2·5² = 25 m."},
{m:"MRUA · FRENADO",q:"Un automóvil circula a 20 m/s y frena con aceleración −4 m/s². ¿Cuánto tarda en detenerse?",a:5,t:.1,u:"s",h:"Al detenerse, v = 0.",s:"0 = 20 − 4t. Por lo tanto t = 5 s."},
{m:"MRUA · CAMBIO DE SENTIDO",q:"Un móvil tiene v₀ = −8 m/s y a = +2 m/s². ¿En qué instante cambia de sentido?",a:4,t:.1,u:"s",h:"El cambio de sentido ocurre cuando v = 0.",s:"0 = −8 + 2t. Entonces t = 4 s."},
{m:"PARABÓLICO · COMPONENTES",q:"Un proyectil se lanza a 20 m/s con un ángulo de 30°. ¿Cuál es su componente vertical inicial?",a:10,t:.1,u:"m/s",h:"v₀y = v₀ sen θ.",s:"v₀y = 20 sen30° = 10 m/s."},
{m:"PARABÓLICO · COMPONENTES",q:"Un proyectil se lanza a 20 m/s con un ángulo de 60°. ¿Cuál es su componente horizontal inicial?",a:10,t:.1,u:"m/s",h:"v₀x = v₀ cos θ.",s:"v₀x = 20 cos60° = 10 m/s."},
{m:"PARABÓLICO · ALTURA",q:"Una pelota se lanza con componente vertical inicial v₀y = 14 m/s. ¿Cuánto tarda en alcanzar su altura máxima?",a:14/9.81,t:.03,u:"s",h:"En la altura máxima, vᵧ = 0.",s:"0 = 14 − 9,81t. Entonces t ≈ 1,43 s."},
{m:"CAÍDA · COMPONENTE VERTICAL",q:"Un objeto se lanza horizontalmente desde una altura de 20 m. ¿Cuánto tarda en llegar al suelo?",a:Math.sqrt(40/9.81),t:.03,u:"s",h:"La velocidad vertical inicial es cero.",s:"0 = 20 − ½·9,81·t². Resulta t ≈ 2,02 s."},
{m:"TRAMOS · VELOCIDAD",q:"Un móvil viaja a 5 m/s durante 4 s y luego acelera a 2 m/s² durante 3 s. ¿Cuál es su velocidad final?",a:11,t:.1,u:"m/s",h:"El primer tramo no modifica la velocidad.",s:"v = 5 + 2·3 = 11 m/s."},
{m:"TRAMOS · DESPLAZAMIENTO",q:"Un móvil viaja a 5 m/s durante 4 s y luego acelera desde 5 m/s a 2 m/s² durante 3 s. ¿Cuál es su desplazamiento total?",a:44,t:.1,u:"m",h:"Calcula por separado el desplazamiento de cada tramo.",s:"Tramo 1: 20 m. Tramo 2: 24 m. Total = 44 m."}
];let ei=0,solved=[];try{solved=JSON.parse(localStorage.getItem("ufro-mov-v4")||"[]")}catch(e){}
function save(){try{localStorage.setItem("ufro-mov-v4",JSON.stringify(solved))}catch(e){}let n=solved.length,p=Math.round(100*n/12);$("solvedCount").textContent=n;$("progressPct").textContent=p+"%";$("progressFill").style.width=p+"%"}
function showE(){let e=E[ei];$("exerciseMeta").textContent=`${e.m} · ${String(ei+1).padStart(2,"0")} / 12`;$("question").textContent=e.q;$("unit").textContent=e.u;$("answer").value="";$("feedback").className="";$("feedback").textContent=""}
$("check").onclick=()=>{let e=E[ei],v=parseFloat($("answer").value);if(Number.isNaN(v)){$("feedback").className="feedback-bad";$("feedback").textContent="Ingresa una respuesta numérica.";return}let ok=Math.abs(v-e.a)<=e.t;$("feedback").className=ok?"feedback-ok":"feedback-bad";$("feedback").textContent=ok?"Correcto. La respuesta es consistente con el modelo.":"Aún no. Revisa unidades, signos y la ecuación elegida.";if(ok&&!solved.includes(ei)){solved.push(ei);save()}};$("hint").onclick=()=>{$("feedback").className="feedback-bad";$("feedback").textContent=E[ei].h};$("solution").onclick=()=>{$("feedback").className="feedback-ok";$("feedback").textContent=E[ei].s};$("next").onclick=()=>{ei=(ei+1)%12;showE()};$("prev").onclick=()=>{ei=(ei+11)%12;showE()};$("clearProgress").onclick=()=>{solved=[];save();showE()};

/* graph click */
function attach(canvas,slider,maxFn,fn){canvas.addEventListener("click",e=>{let r=canvas.getBoundingClientRect(),p=clamp((e.clientX-r.left)/r.width,0,1),t=p*maxFn();slider.value=t;fn(t)})}
attach($("xGraph"),$("timeSlider"),()=>model().T,updateMain);attach($("vGraph"),$("timeSlider"),()=>model().T,updateMain);attach($("aGraph"),$("timeSlider"),()=>model().T,updateMain);
attach($("pgx"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgy"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgvx"),$("projTime"),()=>pstate().tf,updateProj);attach($("pgvy"),$("projTime"),()=>pstate().tf,updateProj);

updateMain(0);renderSegs();updateProj(0);showE();save();
})();